Repository certbot/certbot, pull requests merged in 2018-10, with the labels that each got.

#6414 Add debugging info for Nginx tls-sni and http integration tests purposes
  certbot-nginx/certbot_nginx/http_01.py
  certbot-nginx/certbot_nginx/tls_sni_01.py
  certbot-nginx/tests/boulder-integration.sh
Labels: current sprint

#6411 Stop caching the results of ipv6_info in http01.py
  CHANGELOG.md
  certbot-nginx/certbot_nginx/http_01.py
  certbot-nginx/certbot_nginx/tests/http_01_test.py
  certbot-nginx/certbot_nginx/tls_sni_01.py
Labels: current sprint

#6320 certbot_dns_linode: increase the default propagation interval
  certbot-dns-linode/certbot_dns_linode/__init__.py
  certbot-dns-linode/certbot_dns_linode/dns_linode.py
Labels: area: dns

#6370 Warn manual authenticator users not to remove/undo previous challenges
  CHANGELOG.md
  certbot/plugins/manual.py
  certbot/plugins/manual_test.py
  certbot/tests/acme_util.py
Labels: area: dns, area: manual authenticator, area: ui / ux

#6383 Add and test new nginx parsing abstractions
  certbot-nginx/certbot_nginx/parser_obj.py
  certbot-nginx/certbot_nginx/tests/parser_obj_test.py
  tests/integration/_common.sh
Labels: current sprint

#6374 [Windows] Create the CI logic
  acme/acme/client_test.py
  acme/acme/crypto_util.py
  acme/acme/standalone_test.py
  acme/acme/test_util.py
  appveyor.yml
  certbot/compat.py
  certbot/crypto_util.py
  certbot/display/completer.py
  certbot/display/util.py
  certbot/main.py
  certbot/plugins/manual_test.py
  certbot/plugins/util_test.py
  certbot/plugins/webroot_test.py
  certbot/renewal.py
  certbot/tests/account_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/cli_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/display/completer_test.py
  certbot/tests/display/util_test.py
  certbot/tests/error_handler_test.py
  certbot/tests/hook_test.py
  certbot/tests/lock_test.py
  certbot/tests/log_test.py
  certbot/tests/main_test.py
  certbot/tests/reverter_test.py
  certbot/tests/storage_test.py
  certbot/tests/util.py
  certbot/tests/util_test.py
  certbot/util.py
  tox-win.ini
Labels: current sprint

#6412 Fix ranking of vhosts in Nginx so that all port-matching vhosts come first
  CHANGELOG.md
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
Labels: current sprint

#6437 Fix macOS tests
  .travis.yml
  tests/travis-macos-setup.sh
Labels: area: code health, area: macOS, area: testing

#6438 Update Augeas lens to fix some Apache configuration parsing issues
  CHANGELOG.md
  certbot-apache/certbot_apache/augeas_lens/httpd.aug
Labels: current sprint, has pr
