Repository certbot/certbot, pull requests merged in 2018-04, with the labels that each got.

#5812 Remove build path from SSL_DHPARAM_SRC docs
  docs/api/constants.rst
Labels: area: documentation

#5815 Fix comparison to check values for derivative warning in Nginx
  certbot-nginx/certbot_nginx/configurator.py
Labels: area: nginx

#5811 Support quoted server names in Nginx
  certbot-nginx/certbot_nginx/parser.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/testdata/etc_nginx/sites-enabled/default
Labels: area: nginx, bug

#5818 Document default is ACMEv2
  docs/using.rst
Labels: area: documentation

#5500 If restart fails, try alternative restart command if available
  certbot-apache/certbot_apache/configurator.py
  certbot-apache/certbot_apache/override_centos.py
  certbot-apache/certbot_apache/override_gentoo.py
  certbot-apache/certbot_apache/tests/centos_test.py
  certbot-apache/certbot_apache/tests/gentoo_test.py
Labels: area: apache

#5827 Include testdata
  certbot-dns-google/MANIFEST.in
Labels: area: pkging, area: testing

#5759 Add wildcard field to Authorization resource
  acme/acme/messages.py
Labels: area: acme

#5829 Update certbot-auto and versions to reflect 0.23.0 release
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#5754 Add note to developer guide docs about installing docs extras. (#4946)
  docs/contributing.rst
Labels: area: documentation

#5468 PluginStorage to store variables between invocations.
  certbot/errors.py
  certbot/plugins/common.py
  certbot/plugins/storage.py
  certbot/plugins/storage_test.py
Labels: current sprint

#5852 Use older boulder version for tests
  tests/boulder-fetch.sh
Labels: area: boulder, area: testing

#5861 Get mypy tox env running in the current setup
  .gitignore
  setup.py
  tools/dev_constraints.txt
  tox.ini
Labels: area: code health

#5863 Remove unnecessary test metaclass
  certbot-apache/certbot_apache/tests/http_01_test.py
Labels: area: apache, area: testing

#5865 Help clarify version number
  certbot-apache/certbot_apache/tests/http_01_test.py
Labels: area: code health, area: documentation, area: testing

#5650 Improve style around choosing lineagename
  certbot/client.py
Labels: area: code health, low priority

#5743 Adjust file paths message from Warning to Info.
  certbot/client.py
Labels: area: ui / ux

#5596 Enhance verb
  certbot-apache/certbot_apache/configurator.py
  certbot-apache/certbot_apache/tests/configurator_test.py
  certbot-apache/certbot_apache/tests/debian_test.py
  certbot-apache/certbot_apache/tls_sni_01.py
  certbot/cert_manager.py
  certbot/cli.py
  certbot/client.py
  certbot/display/ops.py
  certbot/main.py
  certbot/plugins/selection.py
  certbot/tests/cert_manager_test.py
  certbot/tests/client_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/main_test.py
Labels: current sprint

#5887 Remove EOL'd Ubuntu from targets.yaml
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#5889 Updated base image to python:2-alpine3.7
  Dockerfile
Labels: area: pkging

#5891 Update good volunteer task to good first issue
  docs/contributing.rst
Labels: area: documentation

#5712 Restore parallel waiting to Route53 plugin
  certbot-dns-route53/certbot_dns_route53/dns_route53.py
Labels: area: dns
