Repository certbot/certbot, pull requests merged in 2018-09, with the labels that each got.

#6338 Update changelog for 0.27.0
  CHANGELOG.md
Labels: area: documentation, area: pkging

#6339 Candidate 0.27.0
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6340 Gitignore should include .pytest_cache/
  .gitignore
Labels: area: code health

#6296 Make Certbot runnable on Windows
  certbot/account.py
  certbot/cert_manager.py
  certbot/client.py
  certbot/compat.py
  certbot/crypto_util.py
  certbot/display/util.py
  certbot/lock.py
  certbot/log.py
  certbot/main.py
  certbot/plugins/util.py
  certbot/plugins/util_test.py
  certbot/plugins/webroot.py
  certbot/reverter.py
  certbot/tests/configuration_test.py
  certbot/tests/display/util_test.py
  certbot/tests/lock_test.py
  certbot/tests/main_test.py
  certbot/tests/util.py
  certbot/tests/util_test.py
Labels: current sprint

#6353 Add better error handling around release signatures
  tools/_release.sh
Labels: area: code health, area: pkging

#6223 Exclude one-time use parameters. Fixes #6118
  certbot-nginx/certbot_nginx/parser.py
Labels: area: nginx

#6361 Connect AppVeyor to the certbot git repository
  appveyor.yml
Labels: area: testing, area: windows, current sprint, high priority, more-info

#6381 Update parser to match new Nginx functionality
  CHANGELOG.md
  certbot-nginx/certbot_nginx/nginxparser.py
  certbot-nginx/certbot_nginx/tests/nginxparser_test.py
Labels: area: nginx, bug

#6388 revoke accepts --cert-name
  CHANGELOG.md
  certbot/cli.py
  certbot/main.py
  certbot/tests/main_test.py
  tests/certbot-boulder-integration.sh
Labels: area: cert management, current sprint
