Repository certbot/certbot, pull requests merged in 2018-03, with the labels that each got.

#5638 Suggest DNS authenticator when it's needed
  certbot/auth_handler.py
  certbot/tests/auth_handler_test.py
Labels: area: error handling, area: ui / ux

#5641 Drop minimum integration test coverage to 63
  tests/boulder-integration.sh
Labels: area: testing

#5635 Add basic ACMEv2 integration tests
  .travis.yml
  tests/boulder-fetch.sh
  tests/boulder-integration.sh
  tests/integration/_common.sh
Labels: area: testing

#5619 Nginx plugin wildcard support for ACMEv2
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/display_ops.py
  certbot-nginx/certbot_nginx/http_01.py
  certbot-nginx/certbot_nginx/obj.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/display_ops_test.py
  certbot-nginx/certbot_nginx/tests/tls_sni_01_test.py
  certbot-nginx/certbot_nginx/tls_sni_01.py
Labels: area: acme, area: nginx

#5636 Add user friendly wildcard error for ACMEv1
  acme/acme/client.py
  acme/acme/client_test.py
  acme/acme/errors.py
  certbot/client.py
  certbot/tests/client_test.py
Labels: area: error handling, area: ui / ux

#5639 Remove leading *. from default cert name.
  certbot/client.py
  certbot/tests/client_test.py
Labels: area: ui / ux

#5648 Fix ipv6only detection
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/testdata/etc_nginx/sites-enabled/ipv6ssl.com
Labels: area: nginx

#5628 Add DNS Dockerfiles
  certbot-dns-cloudflare/Dockerfile
  certbot-dns-cloudxns/Dockerfile
  certbot-dns-digitalocean/Dockerfile
  certbot-dns-dnsimple/Dockerfile
  certbot-dns-dnsmadeeasy/Dockerfile
  certbot-dns-google/Dockerfile
  certbot-dns-luadns/Dockerfile
  certbot-dns-nsone/Dockerfile
  certbot-dns-rfc2136/Dockerfile
  certbot-dns-route53/Dockerfile
Labels: area: pkging

#5655 Break lockstep between our packages
  .travis.yml
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot-dns-cloudflare/local-oldest-requirements.txt
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/local-oldest-requirements.txt
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/local-oldest-requirements.txt
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/local-oldest-requirements.txt
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/local-oldest-requirements.txt
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/local-oldest-requirements.txt
  certbot-dns-google/setup.py
  certbot-dns-luadns/local-oldest-requirements.txt
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/local-oldest-requirements.txt
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/local-oldest-requirements.txt
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/local-oldest-requirements.txt
  certbot-dns-route53/setup.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  local-oldest-requirements.txt
  setup.py
  tools/pip_install.sh
  tox.ini
Labels: area: pkging, area: testing

#5576 Postfix plugin changes
  certbot-postfix/certbot_postfix/installer.py
  certbot-postfix/certbot_postfix/installer_test.py
  certbot-postfix/certbot_postfix/postconf.py
  certbot-postfix/certbot_postfix/postconf_test.py
  certbot-postfix/certbot_postfix/util.py
Labels: area: postfix

#5669 Don't report coverage on Apache during integration tests
  tests/boulder-integration.sh
  tests/integration/_common.sh
Labels: area: testing

#5668 Fix merge conflicts and add more ACMEv2 integration tests
  .travis.yml
  acme/acme/client.py
  acme/acme/client_test.py
  acme/acme/crypto_util.py
  acme/acme/errors.py
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot-dns-cloudflare/Dockerfile
  certbot-dns-cloudflare/local-oldest-requirements.txt
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/Dockerfile
  certbot-dns-cloudxns/local-oldest-requirements.txt
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/Dockerfile
  certbot-dns-digitalocean/local-oldest-requirements.txt
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/Dockerfile
  certbot-dns-dnsimple/local-oldest-requirements.txt
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/Dockerfile
  certbot-dns-dnsmadeeasy/local-oldest-requirements.txt
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/Dockerfile
  certbot-dns-google/local-oldest-requirements.txt
  certbot-dns-google/setup.py
  certbot-dns-luadns/Dockerfile
  certbot-dns-luadns/local-oldest-requirements.txt
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/Dockerfile
  certbot-dns-nsone/local-oldest-requirements.txt
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/Dockerfile
  certbot-dns-rfc2136/local-oldest-requirements.txt
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/Dockerfile
  certbot-dns-route53/local-oldest-requirements.txt
  certbot-dns-route53/setup.py
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/display_ops.py
  certbot-nginx/certbot_nginx/http_01.py
  certbot-nginx/certbot_nginx/obj.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/display_ops_test.py
  certbot-nginx/certbot_nginx/tests/testdata/etc_nginx/sites-enabled/ipv6ssl.com
  certbot-nginx/certbot_nginx/tests/tls_sni_01_test.py
  certbot-nginx/certbot_nginx/tls_sni_01.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  certbot/client.py
  certbot/crypto_util.py
  certbot/tests/client_test.py
  certbot/tests/crypto_util_test.py
  local-oldest-requirements.txt
  setup.py
  tools/pip_install.sh
  tox.ini
Labels: area: testing

#5681 Upgrade pipstrap to 1.5.1
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/pipstrap.py
Labels: area: certbot-auto

#5687 fix(acme): client._revoke sends default content_type
  acme/acme/client.py
  acme/acme/client_test.py
Labels: area: acme

#5696 Add readthedocs requirements files
  certbot-dns-cloudflare/readthedocs.org.requirements.txt
  certbot-dns-cloudxns/readthedocs.org.requirements.txt
  certbot-dns-digitalocean/readthedocs.org.requirements.txt
  certbot-dns-dnsimple/readthedocs.org.requirements.txt
  certbot-dns-dnsmadeeasy/readthedocs.org.requirements.txt
  certbot-dns-google/readthedocs.org.requirements.txt
  certbot-dns-luadns/readthedocs.org.requirements.txt
  certbot-dns-nsone/readthedocs.org.requirements.txt
  certbot-dns-rfc2136/readthedocs.org.requirements.txt
  certbot-dns-route53/readthedocs.org.requirements.txt
Labels: area: dns, area: documentation

#5688 Update the test-everything branch
  acme/acme/client.py
  acme/acme/client_test.py
  certbot-dns-google/certbot_dns_google/__init__.py
  certbot-dns-google/certbot_dns_google/dns_google.py
  certbot-dns-google/certbot_dns_google/dns_google_test.py
  certbot-dns-route53/certbot_dns_route53/dns_route53.py
  certbot-dns-route53/certbot_dns_route53/dns_route53_test.py
  certbot/auth_handler.py
  certbot/plugins/disco.py
  certbot/plugins/manual.py
  certbot/plugins/manual_test.py
  certbot/tests/auth_handler_test.py
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/pipstrap.py
  tests/boulder-integration.sh
  tests/integration/_common.sh
  tests/manual-dns-auth.sh
  tests/manual-dns-cleanup.sh
Labels: area: testing

#5695 Document resps parameter
  certbot/auth_handler.py
Labels: area: documentation

#5691 Update the changelog to reflect 0.22.0
  CHANGELOG.md
Labels: area: documentation, area: pkging

#5682 Release 0.22.0
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#5699 Put API link at the bottom of DNS plugin docs
  certbot-dns-cloudflare/docs/index.rst
  certbot-dns-cloudxns/docs/index.rst
  certbot-dns-digitalocean/docs/index.rst
  certbot-dns-dnsimple/docs/index.rst
  certbot-dns-dnsmadeeasy/docs/index.rst
  certbot-dns-google/docs/index.rst
  certbot-dns-luadns/docs/index.rst
  certbot-dns-nsone/docs/index.rst
  certbot-dns-rfc2136/docs/index.rst
  certbot-dns-route53/docs/index.rst
  tools/sphinx-quickstart.sh
Labels: area: dns, area: documentation

#5710 Add documentation about DNS plugins and Docker
  docs/install.rst
  docs/using.rst
Labels: area: dns, area: documentation, area: pkging

#5713 Add docs about --server
  docs/install.rst
  docs/using.rst
Labels: area: documentation

#5734 Update instances of acme-staging url to acme-staging-v02
  certbot/constants.py
  certbot/tests/storage_test.py
  certbot/tests/testdata/sample-renewal.conf
  docs/contributing.rst
  examples/dev-cli.ini
Labels: area: acme

#5749 Fix Docker link
  docs/contributing.rst
  docs/install.rst
  docs/using.rst
Labels: area: documentation

#5761 Fix cleanup_challenges call
  certbot/auth_handler.py
  certbot/tests/auth_handler_test.py
Labels: area: encoding/type error

#5707 Allow _acme-challenge as a zone
  certbot-dns-rfc2136/certbot_dns_rfc2136/dns_rfc2136.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/dns_rfc2136_test.py
Labels: area: dns

#5767 Release 0.22.1 and 0.22.2
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: pkging

#5768 Update certbot auto to reflect 0.22 point releases
  certbot-auto
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#5770 Update changelog for 0.22.1 and 0.22.2
  CHANGELOG.md
Labels: area: documentation, area: pkging

#5607 logging: log timestamps as local timezone instead of UTC
  certbot/log.py
  certbot/tests/log_test.py
Labels: area: logging

#5622 make pip_install.sh compatible with POSIX sh(1) again
  tools/pip_install.sh
Labels: area: pkging

#5788 Allow 'default' along with 'default_server' in Nginx
  certbot-nginx/certbot_nginx/obj.py
  certbot-nginx/certbot_nginx/parser.py
  certbot-nginx/certbot_nginx/tests/obj_test.py
Labels: area: nginx, bug

#5791 Google DNS: Mock API discovery to run tests without internet connection.
  certbot-dns-google/certbot_dns_google/dns_google.py
  certbot-dns-google/certbot_dns_google/dns_google_test.py
  certbot-dns-google/certbot_dns_google/testdata/discovery.json
Labels: area: dns, area: testing

#5794 Factor out location_directive_for_achall
  certbot-nginx/certbot_nginx/http_01.py
Labels: area: code health, area: nginx

#5779 fix(auth_handler): cleanup is always called
  certbot/auth_handler.py
  certbot/error_handler.py
  certbot/tests/auth_handler_test.py
  certbot/tests/error_handler_test.py
Labels: area: error handling

#5793 Remove ipv6only=on from duplicated vhosts
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/obj.py
  certbot-nginx/certbot_nginx/parser.py
  certbot-nginx/certbot_nginx/tests/parser_test.py
Labels: area: nginx, bug

#5787 We don't try to add location blocks through a mechanism that checks REPEATABLE_DIRECTIVES, and it wouldn't work as an accurate check even if we did, so just remove it
  certbot-nginx/certbot_nginx/parser.py
Labels: area: code health, area: nginx

#5441 Add integration tests for nginx plugin
  certbot-nginx/tests/boulder-integration.conf.sh
  certbot-nginx/tests/boulder-integration.sh
Labels: area: nginx

#5800 Update oldest tests to test against 0.22.0 versions
  certbot-nginx/local-oldest-requirements.txt
  local-oldest-requirements.txt
Labels: area: testing

#5722 Update default to ACMEv2 server
  certbot/constants.py
Labels: area: acme
