Repository certbot/certbot, pull requests merged in 2018-12, with the labels that each got.

#6549 Fix oldest Certbot version that works with Apache.
  certbot-apache/local-oldest-requirements.txt
Labels: area: code health, area: testing

#6405 Remove duplicate route53 options
  certbot/cli.py
  certbot/tests/cli_test.py
Labels: area: documentation

#6558 Candidate 0.29.0
  CHANGELOG.md
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
  local-oldest-requirements.txt
  setup.py
Labels: area: certbot-auto, area: pkging

#6568 Remove -q/--quiet from pip invocations
  tools/install_and_test.py
  tools/pip_install.py
Labels: area: testing, area: ui / ux

#6601 Update pinned urllib3
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
Labels: area: certbot-auto, area: pkging

#6609 Make tox default to any py3 test
  tox.ini
Labels: area: code health, area: testing
