Repository certbot/certbot, pull requests merged in 2018-07, with the labels that each got.

#6169 Upgrade to the latest cryptography version
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
Labels: area: certbot-auto, area: pkging

#6179 Add Python 3.7 tests
  .travis.yml
  certbot-apache/certbot_apache/tests/apache-conf-files/apache-conf-test
Labels: area: apache, area: testing

#6181 Handle merge conflicts and add Python 3.7 integration tests
  .travis.yml
  certbot-apache/certbot_apache/tests/apache-conf-files/apache-conf-test
Labels: area: testing

#6184 Upgrade pinned josepy version
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
  tools/dev_constraints.txt
Labels: area: certbot-auto, area: code health, area: pkging, area: ui / ux

#6182 Full Python 3.7 support
  tools/dev_constraints.txt
  tox.ini
Labels: area: testing

#6183 Advertise our packages work on Python 3.7.
  acme/setup.py
  certbot-apache/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot-postfix/setup.py
  letshelp-certbot/setup.py
  setup.py
Labels: area: documentation, area: pkging

#5302 Linode DNS Authenticator
  certbot-dns-linode/Dockerfile
  certbot-dns-linode/LICENSE.txt
  certbot-dns-linode/MANIFEST.in
  certbot-dns-linode/README.rst
  certbot-dns-linode/certbot_dns_linode/__init__.py
  certbot-dns-linode/certbot_dns_linode/dns_linode.py
  certbot-dns-linode/certbot_dns_linode/dns_linode_test.py
  certbot-dns-linode/docs/.gitignore
  certbot-dns-linode/docs/Makefile
  certbot-dns-linode/docs/api.rst
  certbot-dns-linode/docs/api/dns_linode.rst
  certbot-dns-linode/docs/conf.py
  certbot-dns-linode/docs/index.rst
  certbot-dns-linode/docs/make.bat
  certbot-dns-linode/local-oldest-requirements.txt
  certbot-dns-linode/readthedocs.org.requirements.txt
  certbot-dns-linode/setup.cfg
  certbot-dns-linode/setup.py
  certbot/cli.py
  certbot/constants.py
  certbot/plugins/disco.py
  certbot/plugins/selection.py
  docs/packaging.rst
  docs/using.rst
  tools/release.sh
  tools/venv.sh
  tools/venv3.sh
  tox.cover.sh
  tox.ini
Labels: Needs Review, area: dns

#6189 Always save server value in renewal conf file
  certbot/storage.py
  certbot/tests/storage_test.py
Labels: area: acme, area: renewal

#5701 Sakura Cloud DNS Authenticator
  certbot-dns-sakuracloud/Dockerfile
  certbot-dns-sakuracloud/LICENSE.txt
  certbot-dns-sakuracloud/MANIFEST.in
  certbot-dns-sakuracloud/README.rst
  certbot-dns-sakuracloud/certbot_dns_sakuracloud/__init__.py
  certbot-dns-sakuracloud/certbot_dns_sakuracloud/dns_sakuracloud.py
  certbot-dns-sakuracloud/certbot_dns_sakuracloud/dns_sakuracloud_test.py
  certbot-dns-sakuracloud/docs/.gitignore
  certbot-dns-sakuracloud/docs/Makefile
  certbot-dns-sakuracloud/docs/api.rst
  certbot-dns-sakuracloud/docs/api/dns_sakuracloud.rst
  certbot-dns-sakuracloud/docs/conf.py
  certbot-dns-sakuracloud/docs/index.rst
  certbot-dns-sakuracloud/docs/make.bat
  certbot-dns-sakuracloud/readthedocs.org.requirements.txt
  certbot-dns-sakuracloud/setup.cfg
  certbot-dns-sakuracloud/setup.py
  certbot/cli.py
  certbot/constants.py
  certbot/plugins/disco.py
  certbot/plugins/selection.py
  tools/release.sh
  tools/venv.sh
  tools/venv3.sh
  tox.cover.sh
  tox.ini
Labels: Needs Review, area: dns

#6195 Don't use quoted None for plugins in the config
  certbot/main.py
  certbot/plugins/selection.py
  certbot/tests/storage_test.py
Labels: area: code health, area: ui / ux

#5702 Gehirn Infrastracture Service DNS Authenticator
  certbot-dns-gehirn/Dockerfile
  certbot-dns-gehirn/LICENSE.txt
  certbot-dns-gehirn/MANIFEST.in
  certbot-dns-gehirn/README.rst
  certbot-dns-gehirn/certbot_dns_gehirn/__init__.py
  certbot-dns-gehirn/certbot_dns_gehirn/dns_gehirn.py
  certbot-dns-gehirn/certbot_dns_gehirn/dns_gehirn_test.py
  certbot-dns-gehirn/docs/.gitignore
  certbot-dns-gehirn/docs/Makefile
  certbot-dns-gehirn/docs/api.rst
  certbot-dns-gehirn/docs/api/dns_gehirn.rst
  certbot-dns-gehirn/docs/conf.py
  certbot-dns-gehirn/docs/index.rst
  certbot-dns-gehirn/docs/make.bat
  certbot-dns-gehirn/readthedocs.org.requirements.txt
  certbot-dns-gehirn/setup.cfg
  certbot-dns-gehirn/setup.py
  certbot/cli.py
  certbot/constants.py
  certbot/plugins/disco.py
  certbot/plugins/selection.py
  tools/release.sh
  tools/venv.sh
  tools/venv3.sh
  tox.cover.sh
  tox.ini
Labels: Needs Review, area: dns

#6196 Fix broken fedora links
  docs/packaging.rst
Labels: area: documentation, area: pkging, area: testing

#5423 OVH DNS Authenticator
  certbot-dns-ovh/Dockerfile
  certbot-dns-ovh/LICENSE.txt
  certbot-dns-ovh/MANIFEST.in
  certbot-dns-ovh/README.rst
  certbot-dns-ovh/certbot_dns_ovh/__init__.py
  certbot-dns-ovh/certbot_dns_ovh/dns_ovh.py
  certbot-dns-ovh/certbot_dns_ovh/dns_ovh_test.py
  certbot-dns-ovh/docs/.gitignore
  certbot-dns-ovh/docs/Makefile
  certbot-dns-ovh/docs/api.rst
  certbot-dns-ovh/docs/api/dns_ovh.rst
  certbot-dns-ovh/docs/conf.py
  certbot-dns-ovh/docs/index.rst
  certbot-dns-ovh/docs/make.bat
  certbot-dns-ovh/local-oldest-requirements.txt
  certbot-dns-ovh/readthedocs.org.requirements.txt
  certbot-dns-ovh/setup.cfg
  certbot-dns-ovh/setup.py
  certbot/cli.py
  certbot/constants.py
  certbot/plugins/disco.py
  certbot/plugins/selection.py
  docs/cli-help.txt
  docs/packaging.rst
  docs/using.rst
  tools/release.sh
  tools/venv.sh
  tools/venv3.sh
  tox.cover.sh
  tox.ini
Labels: area: dns

#6152 Update default to ACMEv2 server
  certbot/constants.py
Labels: area: acme, current sprint

#6198 Remove linode and ovh links which aren't valid yet.
  docs/packaging.rst
Labels: area: documentation, area: testing

#6205 Add 0.26.0 changelog
  CHANGELOG.md
Labels: area: documentation

#6206 Update autos, version numbers, and docs
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6216 Fix account tests
  certbot/tests/account_test.py
Labels: area: code health, area: testing

#6250 Bump the acme version needed for account reuse
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  local-oldest-requirements.txt
  setup.py
Labels: area: pkging

#6273 Files with multiple vhosts are fine
  certbot-apache/certbot_apache/display_ops.py
Labels: area: apache, area: ui / ux

#6220 Switch to codecov
  .travis.yml
  README.rst
  tox.cover.sh
Labels: area: code health, area: testing
