Repository certbot/certbot, pull requests merged in 2018-05, with the labels that each got.

#5879 New interfaces for installers to run tasks on renew verb
  certbot/cli.py
  certbot/constants.py
  certbot/interfaces.py
  certbot/main.py
  certbot/renewal.py
  certbot/tests/main_test.py
  certbot/tests/renewupdater_test.py
  certbot/updater.py
Labels: area: install, area: renewal

#5915 Update changelog for 0.24.0
  CHANGELOG.md
Labels: area: documentation, area: pkging

#5919 Correct metaclass usage everywhere
  acme/acme/challenges.py
  certbot/interfaces.py
Labels: area: code health

#5937 Temporarily disable apacheconftest
  .travis.yml
Labels: area: testing

#5949 Specify that every domain name needs to be under a server_name directive
  certbot-nginx/certbot_nginx/configurator.py
Labels: area: nginx, area: ui / ux

#5954 Revert "disable apacheconftest (#5937)"
  .travis.yml
Labels: area: testing

#5953 Small dev docs improvements
  docs/contributing.rst
  docs/install.rst
Labels: area: documentation

#5959 Add link to pycon issues
  docs/contributing.rst
Labels: area: documentation

#5964 Partially revert #5953
  docs/contributing.rst
Labels: area: documentation

#6017 cd before running tests
  tools/install_and_test.sh
Labels: area: code health, area: testing

#6020 Set correct Nginx server root on FreeBSD and Darwin
  certbot-nginx/certbot_nginx/constants.py
Labels: area: nginx

#5862 Update constants.py
  certbot-nginx/certbot_nginx/constants.py
Labels: current sprint

#5918 Turn off cancel notifications
  .travis.yml
Labels: area: testing

#6034 Add domain to error message when no matching server block found
  certbot-nginx/certbot_nginx/configurator.py
Labels: area: nginx, area: ui / ux, current sprint

#6038 Do not call updaters and deployers when run with --dry-run
  certbot/main.py
  certbot/renewal.py
  certbot/tests/main_test.py
  certbot/tests/renewupdater_test.py
  certbot/updater.py
Labels: current sprint

#6033 Add mypy info to Certbot docs
  docs/contributing.rst
Labels: area: documentation, area: mypy, current sprint
