Repository certbot/certbot, pull requests merged in 2018-02, with the labels that each got.

#5561 Suggest people try the community forum first
  ISSUE_TEMPLATE.md
Labels: area: documentation

#5420 [Docs] restore docs for ppl just using Certbot git master
  docs/contributing.rst
Labels: area: documentation

#5477 Ignore .docker
  .gitignore
Labels: area: code health

#5498 Only add Include for TLS configuration if not already there
  certbot-apache/certbot_apache/configurator.py
  certbot-apache/certbot_apache/tests/configurator_test.py
Labels: area: apache

#5536 Fix install verb
  certbot/cli.py
  certbot/main.py
  certbot/tests/main_test.py
  tests/boulder-integration.sh
Labels: area: install

#5578 Add order support and tests
  acme/acme/client.py
  acme/acme/client_test.py
  acme/acme/errors.py
  acme/acme/messages.py
  acme/acme/messages_test.py
Labels: area: acme, area: testing

#5435 Cleanup dockerfile-dev
  Dockerfile-dev
  docker-compose.yml
Labels: area: testing

#5587 Get common name from CSR in new_order in ClientV2
  acme/acme/client.py
  acme/acme/crypto_util.py
  acme/acme/crypto_util_test.py
  acme/acme/testdata/cert-nocn.der
  certbot/crypto_util.py
Labels: area: acme

#5598 Update order object with returned authorizations
  certbot/client.py
  certbot/tests/client_test.py
Labels: area: acme

#5601 Add finalize_order to shim object, update Certbot to use it
  acme/acme/client.py
  acme/acme/client_test.py
  acme/acme/crypto_util.py
  acme/acme/crypto_util_test.py
  certbot/client.py
  certbot/crypto_util.py
  certbot/main.py
  certbot/renewal.py
  certbot/tests/client_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/util.py
Labels: area: acme

#5605 Drop Python 2.6 and 3.3 support
  .travis.yml
  acme/acme/__init__.py
  acme/acme/crypto_util.py
  acme/acme/crypto_util_test.py
  acme/setup.py
  certbot-apache/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot/log.py
  certbot/main.py
  certbot/plugins/disco.py
  certbot/util.py
  docs/contributing.rst
  docs/install.rst
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  letsencrypt-auto-source/pieces/pipstrap.py
  letsencrypt-auto-source/tests/auto_test.py
  letshelp-certbot/letshelp_certbot/apache.py
  letshelp-certbot/setup.py
  setup.py
  tests/letstest/scripts/test_tox.sh
  tests/run_http_server.py
  tools/install_and_test.sh
  tox.ini
Labels: area: code health, area: pkging
