Repository certbot/certbot, pull requests merged in 2018-06, with the labels that each got.

#5901 Add --reuse-key feature
  certbot/cli.py
  certbot/client.py
  certbot/constants.py
  certbot/renewal.py
  certbot/tests/main_test.py
  tests/boulder-integration.sh
Labels: current sprint

#5873 Remove unneeded sys import
  acme/setup.py
  certbot-apache/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  letshelp-certbot/setup.py
  setup.py
Labels: area: code health, area: pkging

#5902 Reuse ACMEv1 accounts for ACMEv2
  certbot/account.py
  certbot/configuration.py
  certbot/constants.py
  certbot/tests/account_test.py
Labels: area: performance, area: ui / ux, current sprint, feature request

#6068 Allow multiple add_headers directives
  certbot-nginx/certbot_nginx/parser.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/parser_test.py
  certbot-nginx/certbot_nginx/tests/testdata/etc_nginx/sites-enabled/headers.com
Labels: area: nginx, area: security enhancements, current sprint

#5944 Automatically select among default vhosts if we have a port preference in nginx
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
Labels: area: nginx, bug, current sprint

#6076 Update changelog for 0.25.0
  CHANGELOG.md
Labels: area: documentation, area: pkging

#6077 Stop testing against Debian 7
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#6078 Upgrade pinned twine version
  tools/dev_constraints.txt
Labels: area: code health, area: pkging

#6075 Update certbot-auto and version numbers
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6091 Fix for #6085
  acme/MANIFEST.in
  acme/pytest.ini
Labels: area: pkging, area: testing

#6109 Release 0.25.1
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-google/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6110 0.25.1 update for master
  certbot-auto
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6111 Add 0.25.1 changelog
  CHANGELOG.md
Labels: area: documentation, area: pkging

#6112 Used packaged acme in oldest tests
  certbot-apache/local-oldest-requirements.txt
  certbot-dns-route53/local-oldest-requirements.txt
  local-oldest-requirements.txt
Labels: area: code health, area: testing

#6115 Remove comment about renewer
  certbot/main.py
Labels: area: code health, area: documentation

#6113 Separate integration coverage
  certbot-nginx/tests/boulder-integration.sh
  tests/boulder-integration.sh
Labels: area: code health, area: testing

#6133 docs: move warning about distro provided renewal
  docs/using.rst
Labels: area: debian / ubuntu, area: documentation

#6134 Reuse ACMEv1 accounts for ACMEv2 in production
  certbot/constants.py
  certbot/tests/account_test.py
Labels: area: performance, area: ui / ux, current sprint, feature request

#6120 Improve UA default in docs
  certbot/client.py
  certbot/tests/client_test.py
  tools/release.sh
Labels: area: documentation

#6137 Show both possible Nginx default server root values in docs
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/constants.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
Labels: area: documentation, current sprint

#6144 Partially revert "Implement TLS-ALPN-01 challenge and standalone TLS-ALPN server (#5894)"
  acme/acme/challenges.py
  acme/acme/challenges_test.py
  acme/acme/crypto_util.py
  acme/acme/crypto_util_test.py
  acme/acme/standalone.py
  acme/acme/standalone_test.py
  acme/acme/testdata/README
  acme/acme/testdata/rsa1024_cert.pem
Labels: area: acme, area: code health

#6097 Interactive certificate selection with install verb
  certbot/main.py
  certbot/tests/main_test.py
Labels: current sprint

#6143 Update cli-help.txt to use generic values
  docs/cli-help.txt
Labels: area: documentation

#6149 Fix server_root default tests on macOS
  certbot-nginx/certbot_nginx/tests/configurator_test.py
Labels: area: macOS, area: nginx, area: testing

#6117 Use greater than or equal to in requirements.
  certbot-apache/setup.py
  certbot-dns-route53/setup.py
  certbot-nginx/setup.py
  certbot-postfix/setup.py
  setup.py
Labels: area: code health, area: pkging

#6156 Use account reuse symlink logic when loading an account
  certbot/account.py
  certbot/tests/account_test.py
Labels: area: renewal, bug, current sprint

#6159 Add --disable=locally-enabled to .pylintrc.
  .pylintrc
Labels: area: code health, area: testing
