Repository certbot/certbot, pull requests merged in 2018-11, with the labels that each got.

#6456 Dummy AWS credentials for Route53 tests to prevent outbound connections
  CHANGELOG.md
  certbot-dns-route53/certbot_dns_route53/dns_route53_test.py
Labels: current sprint

#6442 Use the ACMEv2 newNonce endpoint when a new nonce is needed
  CHANGELOG.md
  acme/acme/client.py
  acme/acme/client_test.py
Labels: current sprint

#6483 Release 0.28.0 part 2
  CHANGELOG.md
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6435 [Windows|Unix] Rewrite bash scripts for tests into python
  .travis.yml
  Dockerfile-dev
  appveyor.yml
  certbot-compatibility-test/Dockerfile
  certbot-postfix/README.rst
  certbot/tests/util.py
  docs/contributing.rst
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/bootstrappers/arch_common.sh
  letsencrypt-auto-source/pieces/pipstrap.py
  tests/letstest/scripts/test_apache2.sh
  tests/letstest/scripts/test_tox.sh
  tests/lock_test.py
  tests/modification-check.py
  tests/modification-check.sh
  tools/_venv_common.py
  tools/_venv_common.sh
  tools/install_and_test.py
  tools/install_and_test.sh
  tools/merge_requirements.py
  tools/pip_install.py
  tools/pip_install.sh
  tools/pip_install_editable.py
  tools/pip_install_editable.sh
  tools/readlink.py
  tools/venv.py
  tools/venv.sh
  tools/venv3.py
  tools/venv3.sh
  tox-win.ini
  tox.cover.py
  tox.cover.sh
  tox.ini
Labels: current sprint

#6518 Fix up environment variable use in venv creation scripts
  tools/_venv_common.py
Labels: area: code health, area: testing

#6489 Automation for changelog changes during release
  tools/_changelog_top.txt
  tools/_release.sh
Labels: area: pkging

#6517 Don't mention _venv_common.sh in certbot-auto.
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/bootstrappers/arch_common.sh
Labels: area: certbot-auto, area: code health

#6525 Fixed Typo
  certbot-dns-google/certbot_dns_google/__init__.py
Labels: area: 3rd party, area: dns

#6488 Clarify letsencrypt-auto to certbot-auto message
  certbot/cli.py
Labels: area: ui / ux

#6538 Ask people not to rewrite commits.
  docs/contributing.rst
Labels: area: documentation

#6516 Whitelist docker-compose in tox.ini
  tox.ini
Labels: area: code health, area: testing, area: ui / ux
