Repository certbot/certbot, pull requests merged in 2019-10, with the labels that each got.

#7414 Keep compatibility with IE11 in the Nginx plugin
  CHANGELOG.md
  certbot-nginx/certbot_nginx/constants.py
  certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx-old.conf
  certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx-tls12-only.conf
  certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx-tls13-session-tix-on.conf
  certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx.conf
Labels: area: nginx, area: security

#7421 Add test farm tests for Debian 10
  tests/letstest/apache2_targets.yaml
  tests/letstest/targets.yaml
Labels: area: debian / ubuntu, area: testing

#7431 Use shared variable group
  .azure-pipelines/INSTALL.md
  .azure-pipelines/templates/tests-suite.yml
Labels: area: code health, area: testing

#7432 Add final newlines to files
  .azure-pipelines/advanced.yml
  .azure-pipelines/main.yml
  .azure-pipelines/templates/installer-tests.yml
Labels: area: code health, area: testing

#7433 Upload coverage for integration tests
  .azure-pipelines/templates/tests-suite.yml
Labels: area: testing

#7455 Run nightly on Azure even if no commits landed
  .azure-pipelines/advanced.yml
Labels: area: testing, area: windows

#7453 Remove warning about 3 year old letsencrypt-auto
  certbot/cli.py
Labels: area: certbot-auto, area: code health

#7458 Require newer versions of oauth2client
  CHANGELOG.md
  certbot-dns-google/setup.py
  tools/dev_constraints.txt
  tools/oldest_constraints.txt
Labels: area: dns, area: pkging, area: testing

#7460 Run at 4:00AM UTC not 0:04AM UTC.
  .azure-pipelines/advanced.yml
Labels: area: testing, area: windows

#7459 Update pluggy pinning
  tools/dev_constraints.txt
Labels: area: code health, area: testing

#7440 Remove AppVeyor
  appveyor.yml
  tox.cover.py
Labels: area: code health, area: testing

#7410 Remove skip_unless cruft
  acme/acme/test_util.py
  certbot/tests/util.py
Labels: area: code health, area: testing

#7268 Migrate certbot-auto users on CentOS 6 to Python 3.6
  .travis.yml
  CHANGELOG.md
  letsencrypt-auto-source/Dockerfile.redhat6
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  letsencrypt-auto-source/pieces/bootstrappers/rpm_common_base.sh
  letsencrypt-auto-source/pieces/bootstrappers/rpm_python3.sh
  letsencrypt-auto-source/pieces/bootstrappers/rpm_python3_legacy.sh
  letsencrypt-auto-source/tests/centos6_tests.sh
  letsencrypt-auto-source/tests/oraclelinux6_tests.sh
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/scripts/test_sdists.sh
  tox.ini
Labels: area: certbot-auto, area: code health, area: fedora / redhat / CentOS

#7477 Deprecate certbot.plugins.common.TLSSNI01
  CHANGELOG.md
  certbot-apache/certbot_apache/http_01.py
  certbot/plugins/common.py
  certbot/plugins/common_test.py
Labels: area: code health

#7476 Polish changelog
  CHANGELOG.md
Labels: area: documentation

#7479 Remove references to TLS-SNI-01 outside of ACME
  CHANGELOG.md
  certbot-apache/certbot_apache/tests/configurator_test.py
  certbot-apache/docs/api/tls_sni_01.rst
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/http_01.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/http_01_test.py
  certbot-nginx/docs/api/tls_sni_01.rst
  certbot/auth_handler.py
  certbot/cli.py
  certbot/tests/acme_util.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cli_test.py
  certbot/tests/renewal_test.py
  docs/contributing.rst
Labels: area: code health
