Repository certbot/certbot, pull requests merged in 2019-08, with the labels that each got.

#7287 [Critical] Fix virtualenv in AppVeyor CI jobs
  tools/dev_constraints.txt
Labels: area: code health, area: testing, area: windows, bug

#7300 Move Nginx TLS configuration files into a specific folder
  certbot-nginx/MANIFEST.in
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx-old.conf
  certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx-tls12-only.conf
  certbot-nginx/certbot_nginx/tls_configs/options-ssl-nginx.conf
Labels: area: nginx

#7302 Fix certbot-auto on RHEL 8
  AUTHORS.md
  CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/scripts/test_sdists.sh
  tests/letstest/targets.yaml
Labels: area: certbot-auto, area: fedora / redhat / CentOS

#7312 Don't run tox -e cover.
  docs/contributing.rst
Labels: area: documentation, area: testing

#7311 Update from 0.37.0 release
  CHANGELOG.md
  acme/setup.py
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: documentation, area: pkging

#7328 Remove some useless config entries from .travis.yml
  .travis.yml
Labels: area: code health, area: testing

#7326 [Windows] Fix closing files descriptors during unit tests
  certbot-nginx/certbot_nginx/tests/util.py
  certbot/compat/filesystem.py
  certbot/tests/compat/filesystem_test.py
  certbot/tests/util.py
Labels: area: code health, area: testing, area: windows

#7349 Use latest RHEL 7 AMI
  tests/letstest/targets.yaml
Labels: area: code health, area: fedora / redhat / CentOS, area: testing

#7335 [Windows] Ensure relpath is executed between paths in the same drive
  certbot-nginx/certbot_nginx/tests/parser_test.py
  certbot/tests/cli_test.py
Labels: area: testing, area: windows

#7336 Update Debian instructions in docs
  docs/install.rst
Labels: area: debian / ubuntu, area: documentation
