Repository certbot/certbot, pull requests merged in 2019-04, with the labels that each got.

#6866 [Windows|Unix] Reimplement reverter logic to make it cross-platform compatible
  certbot/reverter.py
  certbot/tests/reverter_test.py
Labels: area: code health, area: windows, current sprint

#6784 Fix CentOS 6 installer issue
  CHANGELOG.md
  certbot-apache/certbot_apache/override_centos.py
  certbot-apache/certbot_apache/parser.py
  certbot-apache/certbot_apache/tests/centos6_test.py
  certbot-apache/certbot_apache/tests/testdata/centos6_apache/apache/httpd/conf.d/README
  certbot-apache/certbot_apache/tests/testdata/centos6_apache/apache/httpd/conf.d/ssl.conf
  certbot-apache/certbot_apache/tests/testdata/centos6_apache/apache/httpd/conf.d/test.example.com.conf
  certbot-apache/certbot_apache/tests/testdata/centos6_apache/apache/httpd/conf.d/welcome.conf
  certbot-apache/certbot_apache/tests/testdata/centos6_apache/apache/httpd/conf/httpd.conf
Labels: current sprint

#6910 Fix typo in changelog.
  CHANGELOG.md
Labels: area: documentation

#6909 Correct changelog to mention acme changes.
  CHANGELOG.md
Labels: area: acme, area: documentation

#6914 Update changelog about #6912 fix.
  CHANGELOG.md
Labels: area: documentation

#6915 Prepare for the 0.33.1 release.
  CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
Labels: area: certbot-auto, area: documentation, area: pkging

#6916 Tell people to join Mattermost, not IRC
  docs/contributing.rst
Labels: area: documentation

#6917 Don't search for plugins once for each config item
  certbot/storage.py
Labels: area: performance

#6920 Branch candidate 0.33.x
  CHANGELOG.md
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6919 Candidate 0.33.1
  CHANGELOG.md
  certbot-auto
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6921 Move fixing oldest reqs to avoid merge conflicts.
  tools/_release.sh
Labels: area: code health, area: pkging, area: ui / ux

#6822 Remove amazon linux test farm targets.
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#6923 Don't run pip tools/venv.py
  docs/contributing.rst
Labels: area: documentation

#6922 Use venv over virtualenv in venv3
  tests/letstest/scripts/test_apache2.sh
  tests/letstest/scripts/test_sdists.sh
  tools/_venv_common.py
  tools/venv.py
  tools/venv3.py
Labels: area: code health, area: testing

#6929 Update the lexicon version used in tests/Docker.
  tools/dev_constraints.txt
Labels: area: dns, area: docker, area: testing

#6934 Improve codecov report integration to CI in Certbot
  .codecov.yml
  .travis.yml
  appveyor.yml
Labels: area: code health

#6938 Add --disable-pip-version-check to pip calls.
  tools/pip_install.py
Labels: area: testing, area: ui / ux

#6830 Move venv symlink check out of leauto_upgrades.
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh
Labels: area: certbot-auto, area: testing

#6943 Add reminder to local-oldest-requirements.txt.
  certbot-apache/local-oldest-requirements.txt
  certbot-dns-cloudflare/local-oldest-requirements.txt
  certbot-dns-cloudxns/local-oldest-requirements.txt
  certbot-dns-digitalocean/local-oldest-requirements.txt
  certbot-dns-dnsimple/local-oldest-requirements.txt
  certbot-dns-dnsmadeeasy/local-oldest-requirements.txt
  certbot-dns-gehirn/local-oldest-requirements.txt
  certbot-dns-google/local-oldest-requirements.txt
  certbot-dns-linode/local-oldest-requirements.txt
  certbot-dns-luadns/local-oldest-requirements.txt
  certbot-dns-nsone/local-oldest-requirements.txt
  certbot-dns-ovh/local-oldest-requirements.txt
  certbot-dns-rfc2136/local-oldest-requirements.txt
  certbot-dns-route53/local-oldest-requirements.txt
  certbot-dns-sakuracloud/local-oldest-requirements.txt
  certbot-nginx/local-oldest-requirements.txt
  certbot-postfix/local-oldest-requirements.txt
  local-oldest-requirements.txt
Labels: area: code health, area: documentation, area: testing

#6954 Add back used sys import.
  setup.py
Labels: area: pkging, area: testing

#6957 Remove slash from path
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
Labels: area: testing

#6956 Update Fedora AMI
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#6588 Added support for linode version 4 tokens
  CHANGELOG.md
  certbot-dns-linode/certbot_dns_linode/__init__.py
  certbot-dns-linode/certbot_dns_linode/dns_linode.py
  certbot-dns-linode/certbot_dns_linode/dns_linode_test.py
  certbot-dns-linode/local-oldest-requirements.txt
  certbot-dns-linode/setup.py
Labels: area: dns

#6995 Print warning when certbot-auto has insecure permissions.
  CHANGELOG.md
  certbot/cli.py
  certbot/constants.py
  certbot/tests/cli_test.py
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  letsencrypt-auto-source/pieces/check_permissions.py
  letsencrypt-auto-source/tests/auto_test.py
  tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh
Labels: area: certbot-auto, area: error handling, area: security

#7008 Update Lexicon dependency in dnsimple
  certbot-dns-dnsimple/setup.py
  tools/_release.sh
Labels: area: dns, area: pkging

#7002 Update test farm version of boulder to current master
  tests/letstest/multitester.py
  tests/letstest/scripts/boulder_config.sh
Labels: area: testing

#6993 Send a POST-as-GET request to query registration in ACME v2
  CHANGELOG.md
  acme/acme/client.py
Labels: area: acme
