Repository certbot/certbot, pull requests merged in 2019-07, with the labels that each got.

#7215 Install Python3 only dev tools with tools/venv3.py
  tools/_venv_common.py
  tools/venv.py
  tools/venv3.py
Labels: area: code health, feature request

#7226 Document pytest packaging problems
  docs/packaging.rst
Labels: area: documentation, area: pkging

#7157 [Windows|Linux] Launch integration tests on Pebble without Docker
  .gitignore
  certbot-apache/certbot_apache/tests/apache-conf-files/apache-conf-test-pebble.py
  certbot-ci/certbot_integration_tests/assets/cert.pem
  certbot-ci/certbot_integration_tests/assets/key.pem
  certbot-ci/certbot_integration_tests/conftest.py
  certbot-ci/certbot_integration_tests/nginx_tests/nginx_config.py
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-ci/certbot_integration_tests/utils/pebble_artifacts.py
Labels: area: testing

#7232 Remove test symlink.
  test
Labels: area: code health

#7223 Make PR template a checklist and suggest mypy
  pull_request_template.md
Labels: area: code health, area: documentation, area: mypy

#7224 Add mypy to contributing.rst checklist.
  docs/contributing.rst
Labels: area: code health, area: documentation, area: mypy

#7259 Update pexpect to fix Python 3.7 dev venvs.
  tools/dev_constraints.txt
Labels: area: code health

#7272 Remove duplicate, failing oldest tests.
  .travis.yml
Labels: area: testing

#6986 Refer to ubuntu in install.rst
  docs/install.rst
Labels: area: debian / ubuntu, area: documentation

#7284 Bump timeout waiting for ACME server to 4 minutes.
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-ci/certbot_integration_tests/utils/misc.py
Labels: area: code health, area: testing
