Repository certbot/certbot, pull requests merged in 2019-06, with the labels that each got.

#7102 Update Fedora AMI
  tests/letstest/apache2_targets.yaml
  tests/letstest/scripts/set_python_envvars.sh
  tests/letstest/scripts/test_apache2.sh
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh
  tests/letstest/scripts/test_sdists.sh
  tests/letstest/targets.yaml
  tools/simple_http_server.py
Labels: area: testing

#7112 Add explanation of the purpose of test_tests.sh.
  tests/letstest/scripts/test_tests.sh
Labels: area: documentation, area: testing

#7108 Configure the stale bot
  .github/stale.yml
Labels: stale

#7054 Validate OCSP responses in case an explicit responder is designated
  certbot/ocsp.py
  certbot/tests/ocsp_test.py
  certbot/tests/testdata/google_certificate.pem
  certbot/tests/testdata/google_issuer_certificate.pem
  certbot/tests/testdata/ocsp_certificate.pem
  certbot/tests/testdata/ocsp_issuer_certificate.pem
  certbot/tests/testdata/ocsp_responder_certificate.pem
Labels: area: acme, area: ocsp

#7122 Add changelog entry about #7054.
  CHANGELOG.md
Labels: area: documentation

#7129 Improve Apache error message when run with insufficient privileges
  CHANGELOG.md
  certbot-apache/certbot_apache/configurator.py
Labels: area: apache, area: error handling, area: ui / ux

#7133 Ask for updates, the issue isn't stale.
  .github/stale.yml
Labels: area: ui / ux

#7142 Fix dns rfc2136
  CHANGELOG.md
  certbot-dns-rfc2136/certbot_dns_rfc2136/__init__.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/dns_rfc2136.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/dns_rfc2136_test.py
Labels: area: dns

#7146 Remove list of modified packages from changelog.
  CHANGELOG.md
  pull_request_template.md
  tools/_changelog_top.txt
Labels: area: documentation, area: pkging

#7097 Remove the Postfix plugin
  .travis.yml
  certbot-postfix/LICENSE.txt
  certbot-postfix/MANIFEST.in
  certbot-postfix/README.rst
  certbot-postfix/certbot_postfix/__init__.py
  certbot-postfix/certbot_postfix/constants.py
  certbot-postfix/certbot_postfix/installer.py
  certbot-postfix/certbot_postfix/postconf.py
  certbot-postfix/certbot_postfix/tests/__init__.py
  certbot-postfix/certbot_postfix/tests/installer_test.py
  certbot-postfix/certbot_postfix/tests/postconf_test.py
  certbot-postfix/certbot_postfix/tests/util_test.py
  certbot-postfix/certbot_postfix/util.py
  certbot-postfix/docs/.gitignore
  certbot-postfix/docs/Makefile
  certbot-postfix/docs/api.rst
  certbot-postfix/docs/api/installer.rst
  certbot-postfix/docs/api/postconf.rst
  certbot-postfix/docs/conf.py
  certbot-postfix/docs/index.rst
  certbot-postfix/docs/make.bat
  certbot-postfix/local-oldest-requirements.txt
  certbot-postfix/setup.cfg
  certbot-postfix/setup.py
  certbot/plugins/disco.py
  docs/using.rst
  tools/_venv_common.py
  tools/install_and_test.py
  tox.cover.py
  tox.ini
Labels: area: code health

#7001 Move nginx_compat to nightly tests
  .travis.yml
Labels: area: code health, area: compatibility-test, area: testing

#7073 Add executable scripts to start certbot and acme server in certbot-ci
  .gitignore
  certbot-ci/certbot_integration_tests/certbot_tests/context.py
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot-ci/certbot_integration_tests/conftest.py
  certbot-ci/certbot_integration_tests/nginx_tests/context.py
  certbot-ci/certbot_integration_tests/nginx_tests/test_main.py
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-ci/certbot_integration_tests/utils/certbot_call.py
  certbot-ci/certbot_integration_tests/utils/constants.py
  certbot-ci/setup.py
  docs/contributing.rst
Labels: area: boulder, area: testing

#7155 Tell people they can add their name to AUTHORS.md.
  pull_request_template.md
Labels: area: documentation

#7156 [Windows|Linux] Use builtin Python proxy capabilities for Certbot-CI
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-ci/certbot_integration_tests/utils/constants.py
  certbot-ci/certbot_integration_tests/utils/proxy.py
Labels: area: testing

#7162 Correct documentation in cli.py
  certbot/cli.py
Labels: area: code health, area: documentation

#7166 Update Ubuntu 18.04 AMI to fix blocking on input
  tests/letstest/apache2_targets.yaml
  tests/letstest/targets.yaml
Labels: area: debian / ubuntu, area: testing

#7167 Upgrade to the latest macOS image
  .travis.yml
Labels: area: macOS, area: testing

#7175 Fix integration tests with Pebble v2.1.0 +
  certbot-ci/certbot_integration_tests/utils/acme_server.py
Labels: area: acme, area: code health, area: testing

#7185 Upgrade compatibility tests to stretch
  certbot-compatibility-test/Dockerfile
Labels: area: code health, area: compatibility-test

#7187 Drop quay.io Docker images
  tools/docker-warning.sh
Labels: area: code health, area: docker

#7189 Add Debian ARM AMI
  tests/letstest/apache2_targets.yaml
  tests/letstest/multitester.py
  tests/letstest/targets.yaml
Labels: area: testing

#7190 Drop support for Ubuntu Trusty
  .travis.yml
  CHANGELOG.md
  certbot-apache/certbot_apache/configurator.py
  letsencrypt-auto-source/Dockerfile.trusty
  letsencrypt-auto-source/rebuild_dependencies.py
  tests/letstest/apache2_targets.yaml
  tests/letstest/scripts/boulder_install.sh
  tests/letstest/targets.yaml
  tox.ini
Labels: area: code health, area: testing

#7052 dns-cloudflare: update URL for obtaining API keys
  certbot-dns-cloudflare/certbot_dns_cloudflare/dns_cloudflare.py
Labels: area: 3rd party, area: code health

#7188 Remove files for old Docker image.
  Dockerfile-old
  tools/docker-warning.sh
Labels: area: code health, area: docker

#7195 Run le_auto_xenial on every PR.
  .travis.yml
Labels: area: testing

#7196 Fix typo in CLI help
  certbot/cli.py
Labels: area: documentation, area: ui / ux

#7197 Fix certbot config_changes
  CHANGELOG.md
  certbot/cli.py
  certbot/client.py
  certbot/main.py
  certbot/reverter.py
  certbot/tests/reverter_test.py
Labels: area: code health, area: ui / ux

#7200 Remove plesk from the list of 3rd party plugins.
  docs/using.rst
Labels: area: 3rd party, area: documentation

#7201 certbot-plugin-gandi is not an installer.
  docs/using.rst
Labels: area: documentation

#7207 Document certbot-auto's code freeze
  docs/contributing.rst
Labels: area: certbot-auto, area: documentation
