Repository certbot/certbot, pull requests merged in 2019-05, with the labels that each got.

#7017 Fix test_leauto_upgrades on Debian 9 and Fedora 29+
  tests/letstest/scripts/test_leauto_upgrades.sh
Labels: area: certbot-auto, area: testing

#7016 Stop certbot-auto from printing blank lines
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh
Labels: area: certbot-auto, area: testing

#7019 Fix oldest tests when local dependencies are used
  .travis.yml
  tools/pip_install.py
Labels: area: testing

#7022 New approach to fix oldest tests when local dependencies are used
  .travis.yml
  tools/pip_install.py
Labels: area: testing

#7023 Update changelog for 0.34.1. (#7021)
  CHANGELOG.md
Labels: area: documentation

#7036 Candidate 0.34.1-2
  CHANGELOG.md
  certbot-auto
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: documentation, area: pkging

#6702 Add FreeBSD specific paths
  CHANGELOG.md
  certbot/compat/misc.py
Labels: area: freebsd

#7056 Revert " Add FreeBSD specific paths (#6702)"
  CHANGELOG.md
  certbot/compat/misc.py
Labels: area: certbot-auto, area: freebsd

#7064 Add disclaimer about EFF MM instance
  docs/contributing.rst
Labels: area: documentation

#7029 Add an option to dns_rfc2136 plugin to specify an authorative base domain.
  CHANGELOG.md
  certbot-dns-rfc2136/certbot_dns_rfc2136/__init__.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/dns_rfc2136.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/dns_rfc2136_test.py
Labels: area: dns

#7061 Add test farm tests requirements file
  tests/letstest/README.md
  tests/letstest/requirements.txt
Labels: area: testing

#7070 Fix cleanup on failure.
  tests/letstest/multitester.py
Labels: area: code health, area: testing

#7079 Regularly print output in the test farm tests
  tests/letstest/multitester.py
Labels: area: testing

#7080 Fix race condition adding tags to instance.
  tests/letstest/multitester.py
Labels: area: code health, area: testing

#7065 Exit with a nonzero status when test farm tests fail
  tests/letstest/multitester.py
Labels: area: code health, area: testing

#7057 Stop sharing state between processes in test farm tests
  tests/letstest/multitester.py
Labels: area: code health, area: testing

#7069 Allow magic profile name none for configuring test farm tests.
  tests/letstest/multitester.py
Labels: area: testing

#7072 Enable test farm tests in Travis
  .travis.yml
  tests/letstest/travis-setup.sh
  tests/letstest/travis-test-farm.pem.enc
  tox.ini
Labels: area: testing

#7101 Revert "Fix unpinned dependencies tests towards botocore and urllib3 (#7081)"
  certbot-dns-route53/setup.py
Labels: area: dns, area: pkging

#7099 Update Ubuntu AMI to 19.04
  tests/letstest/apache2_targets.yaml
  tests/letstest/targets.yaml
Labels: area: testing

#7098 Move IRC notifications to #certbot-devel.
  .travis.yml
Labels: area: code health, area: documentation, area: testing

#7055 Remove dependency on acme in certbot-ci
  certbot-ci/certbot_integration_tests/utils/misc.py
  certbot-ci/setup.py
Labels: area: testing
