Repository certbot/certbot, pull requests merged in 2019-11, with the labels that each got.

#7485 Don't use dev version of Python 3.8
  .travis.yml
Labels: area: code health, area: testing

#7484 Don't use acme.test_util outside of acme
  certbot-compatibility-test/certbot_compatibility_test/testdata/rsa1024_key.pem
  certbot-compatibility-test/certbot_compatibility_test/testdata/rsa1024_key2.pem
  certbot-compatibility-test/certbot_compatibility_test/util.py
Labels: area: code health, area: testing

#7483 Deprecate more code related to TLS-SNI-01
  CHANGELOG.md
  acme/acme/__init__.py
  acme/acme/standalone.py
  acme/acme/standalone_test.py
Labels: area: acme, area: code health

#7493 Describe distributed Certbot components
  docs/contributing.rst
Labels: area: documentation, area: pkging

#7491 Clarify when the changelog should be modified
  pull_request_template.md
Labels: area: code health, area: documentation

#7498 Build Windows installers with pinned dependencies
  setup.py
  windows-installer/construct.py
Labels: area: install, area: windows

#7501 Don't use --agree-dev-preview in tests
  tests/letstest/scripts/test_apache2.sh
  tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh
Labels: area: code health, area: testing

#7504 Pin all build dependencies for the Windows installer
  windows-installer/construct.py
Labels: area: install, area: windows

#7514 Match our Travis logic in Azure
  .azure-pipelines/advanced.yml
  .azure-pipelines/main.yml
Labels: area: code health, area: testing

#7523 Update 0.40.x Azure config
  .azure-pipelines/advanced.yml
  .azure-pipelines/main.yml
Labels: area: code health, area: testing

#7527 Remove tls sni common
  CHANGELOG.md
  certbot/plugins/common.py
  certbot/plugins/common_test.py
Labels: area: code health

#7526 Remove get_systemd_os_info
  CHANGELOG.md
  certbot/tests/util_test.py
  certbot/util.py
Labels: area: code health

#7528 Make uncomplicated modules private
  certbot-apache/certbot_apache/configurator.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  certbot/_internal/__init__.py
  certbot/_internal/account.py
  certbot/_internal/auth_handler.py
  certbot/_internal/cert_manager.py
  certbot/_internal/client.py
  certbot/_internal/error_handler.py
  certbot/_internal/lock.py
  certbot/_internal/main.py
  certbot/_internal/notify.py
  certbot/_internal/ocsp.py
  certbot/_internal/renewal.py
  certbot/_internal/reporter.py
  certbot/_internal/storage.py
  certbot/_internal/updater.py
  certbot/cli.py
  certbot/display/ops.py
  certbot/plugins/common_test.py
  certbot/plugins/enhancements.py
  certbot/tests/account_test.py
  certbot/tests/acme_util.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/cli_test.py
  certbot/tests/client_test.py
  certbot/tests/compat/filesystem_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/error_handler_test.py
  certbot/tests/lock_test.py
  certbot/tests/log_test.py
  certbot/tests/main_test.py
  certbot/tests/notify_test.py
  certbot/tests/ocsp_test.py
  certbot/tests/renewal_test.py
  certbot/tests/renewupdater_test.py
  certbot/tests/reporter_test.py
  certbot/tests/storage_test.py
  certbot/tests/util.py
  certbot/util.py
  docs/api/account.rst
  docs/api/auth_handler.rst
  docs/api/cert_manager.rst
  docs/api/client.rst
  docs/api/error_handler.rst
  docs/api/lock.rst
  docs/api/main.rst
  docs/api/notify.rst
  docs/api/ocsp.rst
  docs/api/renewal.rst
  docs/api/reporter.rst
  docs/api/storage.rst
  setup.py
  tests/lock_test.py
  windows-installer/construct.py
Labels: area: 3rd party, area: documentation

#7535 Remove TLS-SNI objects in ACME
  CHANGELOG.md
  acme/acme/__init__.py
  acme/acme/challenges.py
  acme/acme/challenges_test.py
  acme/acme/standalone.py
  acme/acme/standalone_test.py
  acme/acme/test_util.py
  pytest.ini
Labels: area: acme, area: code health

#7549 Remove python2 and certbot-auto references in Certbot dev setup instructions
  docs/contributing.rst
Labels: area: documentation

#7536 [Windows] Fix certbot renew task failure under NT AUTHORITY\SYSTEM account
  certbot/compat/filesystem.py
Labels: area: windows

#7537 [Windows] Avoid letsencrypt.log permissions error during scheduled certbot renew task
  windows-installer/renew-up.ps1
Labels: area: windows

#7542 Move configuration.py to _internal
  certbot-compatibility-test/certbot_compatibility_test/configurators/apache/common.py
  certbot-compatibility-test/certbot_compatibility_test/configurators/nginx/common.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/http_01_test.py
  certbot-nginx/certbot_nginx/tests/util.py
  certbot/_internal/cert_manager.py
  certbot/_internal/configuration.py
  certbot/_internal/main.py
  certbot/tests/cert_manager_test.py
  certbot/tests/configuration_test.py
  certbot/tests/main_test.py
  certbot/tests/renewal_test.py
  certbot/tests/util.py
  docs/api/configuration.rst
Labels: area: 3rd party, area: documentation

#7557 Fix shebang in rebuild_deps
  letsencrypt-auto-source/rebuild_dependencies.py
Labels: area: certbot-auto

#7543 Internalize modules called by internal plugins
  certbot/_internal/cli.py
  certbot/_internal/client.py
  certbot/_internal/hooks.py
  certbot/_internal/main.py
  certbot/_internal/plugins/manual.py
  certbot/_internal/plugins/selection.py
  certbot/_internal/plugins/webroot.py
  certbot/_internal/renewal.py
  certbot/_internal/storage.py
  certbot/plugins/enhancements.py
  certbot/tests/cli_test.py
  certbot/tests/client_test.py
  certbot/tests/hook_test.py
  certbot/tests/main_test.py
  certbot/tests/renewal_test.py
  certbot/tests/storage_test.py
  docs/api/cli.rst
  docs/api/hooks.rst
Labels: area: 3rd party, area: documentation

#7558 Update pinned dependencies
  CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
  letsencrypt-auto-source/rebuild_dependencies.py
Labels: area: certbot-auto, area: code health, area: fedora / redhat / CentOS

#7560 Disable pylint design checks
  .pylintrc
  acme/acme/challenges.py
  acme/acme/challenges_test.py
  acme/acme/client.py
  acme/acme/client_test.py
  acme/acme/crypto_util.py
  acme/acme/crypto_util_test.py
  acme/acme/jws.py
  acme/acme/standalone.py
  certbot-apache/certbot_apache/configurator.py
  certbot-apache/certbot_apache/obj.py
  certbot-apache/certbot_apache/parser.py
  certbot-apache/certbot_apache/tests/autohsts_test.py
  certbot-apache/certbot_apache/tests/configurator_test.py
  certbot-apache/certbot_apache/tests/parser_test.py
  certbot-apache/certbot_apache/tests/util.py
  certbot-compatibility-test/certbot_compatibility_test/configurators/apache/common.py
  certbot-compatibility-test/certbot_compatibility_test/configurators/common.py
  certbot-compatibility-test/certbot_compatibility_test/configurators/nginx/common.py
  certbot-nginx/certbot_nginx/configurator.py
  certbot-nginx/certbot_nginx/nginxparser.py
  certbot-nginx/certbot_nginx/obj.py
  certbot-nginx/certbot_nginx/tests/configurator_test.py
  certbot-nginx/certbot_nginx/tests/parser_test.py
  certbot-nginx/certbot_nginx/tests/util.py
  certbot/_internal/account.py
  certbot/_internal/cli.py
  certbot/_internal/main.py
  certbot/_internal/plugins/selection.py
  certbot/_internal/renewal.py
  certbot/_internal/storage.py
  certbot/achallenges.py
  certbot/display/util.py
  certbot/interfaces.py
  certbot/tests/account_test.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/cli_test.py
  certbot/tests/client_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/display/util_test.py
  certbot/tests/main_test.py
  certbot/tests/reverter_test.py
  certbot/tests/storage_test.py
Labels: area: code health, area: testing

#7586 Remove unused route53 tools
  certbot-dns-route53/tools/tester.pkoch-macos_sierra.sh
Labels: area: code health, area: dns

#7603 Defines the RenewableCert API
  certbot/certbot/_internal/storage.py
  certbot/certbot/crypto_util.py
  certbot/certbot/interfaces.py
  certbot/certbot/plugins/enhancements.py
  certbot/tests/crypto_util_test.py
  certbot/tests/storage_test.py
Labels: area: 3rd party, area: code health, area: documentation
