Repository certbot/certbot, pull requests merged in 2019-12, with the labels that each got.

#7615 Upgrade to pywin32>=227
  certbot/setup.py
  tools/dev_constraints.txt
  windows-installer/construct.py
Labels: area: code health, area: install, area: windows

#7610 Improve main documentation
  certbot/certbot/_internal/main.py
  certbot/certbot/main.py
Labels: area: code health, area: documentation

#7604 Update 3rd party external plugin info
  certbot/docs/using.rst
Labels: area: documentation

#7614 Add full API documentation
  certbot/docs/api.rst
  certbot/docs/api/achallenges.rst
  certbot/docs/api/certbot.achallenges.rst
  certbot/docs/api/certbot.compat.filesystem.rst
  certbot/docs/api/certbot.compat.misc.rst
  certbot/docs/api/certbot.compat.os.rst
  certbot/docs/api/certbot.compat.rst
  certbot/docs/api/certbot.crypto_util.rst
  certbot/docs/api/certbot.display.ops.rst
  certbot/docs/api/certbot.display.rst
  certbot/docs/api/certbot.display.util.rst
  certbot/docs/api/certbot.errors.rst
  certbot/docs/api/certbot.interfaces.rst
  certbot/docs/api/certbot.main.rst
  certbot/docs/api/certbot.plugins.common.rst
  certbot/docs/api/certbot.plugins.dns_common.rst
  certbot/docs/api/certbot.plugins.dns_common_lexicon.rst
  certbot/docs/api/certbot.plugins.dns_test_common.rst
  certbot/docs/api/certbot.plugins.dns_test_common_lexicon.rst
  certbot/docs/api/certbot.plugins.enhancements.rst
  certbot/docs/api/certbot.plugins.rst
  certbot/docs/api/certbot.plugins.storage.rst
  certbot/docs/api/certbot.plugins.util.rst
  certbot/docs/api/certbot.reverter.rst
  certbot/docs/api/certbot.rst
  certbot/docs/api/certbot.tests.acme_util.rst
  certbot/docs/api/certbot.tests.rst
  certbot/docs/api/certbot.tests.util.rst
  certbot/docs/api/certbot.util.rst
  certbot/docs/api/crypto_util.rst
  certbot/docs/api/display.rst
  certbot/docs/api/errors.rst
  certbot/docs/api/index.rst
  certbot/docs/api/interfaces.rst
  certbot/docs/api/main.rst
  certbot/docs/api/plugins/common.rst
  certbot/docs/api/plugins/dns_common.rst
  certbot/docs/api/plugins/dns_common_lexicon.rst
  certbot/docs/api/plugins/util.rst
  certbot/docs/api/reverter.rst
  certbot/docs/api/util.rst
Labels: area: documentation

#7624 Don't list DNS plugins as alpha quality
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
Labels: area: code health, area: dns, area: documentation, area: pkging

#7622 Release 1.0
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: documentation, area: pkging

#7627 Don't list adding type annotations as a PR requirement
  pull_request_template.md
Labels: area: documentation

#7641 Execute Windows installer integration tests on several Windows versions
  .azure-pipelines/templates/installer-tests.yml
Labels: area: pkging, area: testing, area: windows

#7639 Document that we're not accepting DNS plugins
  certbot/docs/contributing.rst
Labels: area: dns, area: documentation

#7640 Remove warning about dev preview
  certbot/docs/contributing.rst
Labels: area: documentation

#7120 Add docker-compose as a requirement of certbot-ci
  certbot-ci/certbot_integration_tests/conftest.py
  certbot-ci/setup.py
  tools/dev_constraints.txt
Labels: area: code health, area: testing

#7646 Remove other 3.8-dev references
  .travis.yml
Labels: area: code health, area: testing

#7650 Include header files for compilation
  .azure-pipelines/templates/installer-tests.yml
Labels: area: testing, area: windows
