Repository certbot/certbot, pull requests merged in 2019-01, with the labels that each got.

#6602 Pin all dependency installation in the release script (#6584)
  tools/_release.sh
Labels: area: code health, area: pkging, area: testing

#6633 Tell people to update changed package list.
  pull_request_template.md
Labels: area: code health, area: documentation, area: pkging

#6637 Add missing acme.jose attribute.
  CHANGELOG.md
  acme/acme/__init__.py
  acme/acme/jose_test.py
Labels: area: acme, area: code health, area: pkging

#6642 Fix oldest nginx integration tests
  tests/integration/_common.sh
Labels: area: code health, area: testing

#6641 Use HTTPS link to semver.org.
  CHANGELOG.md
Labels: area: documentation

#6647 Stop using staging in apacheconftests
  .travis.yml
  certbot-apache/certbot_apache/tests/apache-conf-files/apache-conf-test
  tests/letstest/scripts/test_apache2.sh
  tox.ini
Labels: area: apache, area: code health, area: testing, current sprint

#6656 Change build status links to travis-ci.com.
  README.rst
Labels: area: documentation

#6658 Clarify behavior for deleting certs as part of revocation
  CHANGELOG.md
  certbot/cli.py
  certbot/main.py
Labels: area: cert management

#6661 Setup cron build with specific jobs
  .travis.yml
Labels: area: code health, area: testing

#6669 Remove reference to latest ACME draft implemented.
  acme/acme/__init__.py
Labels: area: code health, area: documentation

#6679 Remove tls-sni-01 challenges in integration tests
  certbot-nginx/tests/boulder-integration.sh
  tests/certbot-boulder-integration.sh
  tests/integration/_common.sh
Labels: area: code health, area: testing, bug

#6668 Remove ACMEv1 example.
  acme/docs/index.rst
  acme/examples/example_client.py
Labels: area: code health, area: documentation

#6690 Add VIRTUALENV_NO_DOWNLOAD=1 to all calls to virtualenv
  CHANGELOG.md
  Dockerfile-old
  certbot-compatibility-test/Dockerfile
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tools/_release.sh
Labels: area: certbot-auto, area: pip

#6692 Remove commas in filename
  CHANGELOG.md
  certbot-apache/certbot_apache/tests/configurator_test.py
  certbot-apache/certbot_apache/tests/testdata/debian_apache_2_4/augeas_vhosts/apache2/sites-available/old-and-default.conf
  certbot-apache/certbot_apache/tests/testdata/debian_apache_2_4/augeas_vhosts/apache2/sites-enabled/old,default.conf
  certbot-apache/certbot_apache/tests/testdata/debian_apache_2_4/augeas_vhosts/apache2/sites-enabled/old-and-default.conf
Labels: area: apache, area: pip

#6691 Always download the pinned version of pip in pipstrap
  CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/pipstrap.py
Labels: area: certbot-auto, area: pip

#6695 Candidate 0.30.1
  CHANGELOG.md
  certbot-auto
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6696 Candidate 0.30.1 point release
  CHANGELOG.md
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6699 Update setuptools pinned in pipstrap
  CHANGELOG.md
  letsencrypt-auto-source/Dockerfile.centos6
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/pipstrap.py
Labels: area: certbot-auto, area: pkging

#6704 Update setuptools pinned in pipstrap in 0.30.x
  CHANGELOG.md
  letsencrypt-auto-source/Dockerfile.centos6
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/pipstrap.py
Labels: area: certbot-auto, area: pkging

#6709 Candidate 0.30.2 point release
  CHANGELOG.md
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/__init__.py
  docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#6715 No numprocesses in pytest.ini part 2
  pytest.ini
  tox.ini
Labels: area: code health, area: testing

#6700 Update test farm targets
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#6714 Ignore color_scheme warning from IPython.
  pytest.ini
Labels: area: code health, area: testing

#6727 Set --pyargs directly in the files where it is needed.
  tools/install_and_test.py
  tox.cover.py
  tox.ini
Labels: area: code health, area: testing

#6711 [Windows] Fix account paths on Windows when colons are involved
  certbot/account.py
  certbot/compat.py
  certbot/configuration.py
  certbot/tests/account_test.py
  certbot/tests/configuration_test.py
Labels: area: windows
