Repository certbot/certbot, pull requests merged in 2020-05, with the labels that each got.

#7971 Add warning about ignoring our own warnings
  pytest.ini
Labels: area: code health, area: testing

#7972 Drop min certbot coverage
  tox.cover.py
Labels: area: code health, area: testing

#7968 Platform-agnostic method to copy owner and permissions between files
  certbot/certbot/compat/filesystem.py
  certbot/tests/compat/filesystem_test.py
Labels: area: security, area: windows

#7956 Remove passthrough because its no longer needed
  snap/snapcraft.yaml
Labels: area: code health, area: snaps

#7989 ocsp: add support for public key hash ResponderIDs
  certbot/CHANGELOG.md
  certbot/certbot/ocsp.py
  certbot/tests/ocsp_test.py
Labels: area: ocsp, bug, priority: significant

#8000 Print cause of exit in red text
  certbot/certbot/_internal/log.py
Labels: area: error handling, area: ui / ux

#8006 Mention python3-venv in docs
  tests/letstest/README.md
Labels: area: documentation, area: testing

#8003 Remove quay cruft
  certbot/README.rst
Labels: area: code health, area: docker, area: documentation

#7984 Error out earlier in apache installer when mod_ssl is not available
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/tests/configurator_test.py
  certbot/CHANGELOG.md
Labels: area: apache, area: error handling, area: snaps

#8010 Consistent directory mode apply when makedirs is called
  certbot/certbot/compat/filesystem.py
  certbot/tests/compat/filesystem_test.py
Labels: area: security

#8012 Upgrade pinned certbot dependencies
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
Labels: area: certbot-auto, area: docker, area: install

#8009 Add the content interface to Certbot
  snap/snapcraft.yaml
Labels: area: snaps
