Repository certbot/certbot, pull requests merged in 2020-01, with the labels that each got.

#6994 Remove POST-as-GET fallback to GET
  acme/acme/client.py
  acme/tests/client_test.py
Labels: area: acme

#7587 Implement a sunset mechanism in certbot-auto for systems not supported anymore
  certbot/CHANGELOG.md
  letsencrypt-auto-source/Dockerfile.centos6
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  letsencrypt-auto-source/tests/centos6_tests.sh
  letsencrypt-auto-source/tests/uname_wrapper.sh
Labels: area: certbot-auto, area: fedora / redhat / CentOS

#7675 Do not document private members
  acme/docs/conf.py
  certbot-dns-cloudflare/docs/conf.py
  certbot-dns-cloudxns/docs/conf.py
  certbot-dns-digitalocean/docs/conf.py
  certbot-dns-dnsimple/docs/conf.py
  certbot-dns-dnsmadeeasy/docs/conf.py
  certbot-dns-gehirn/docs/conf.py
  certbot-dns-google/docs/conf.py
  certbot-dns-linode/docs/conf.py
  certbot-dns-luadns/docs/conf.py
  certbot-dns-nsone/docs/conf.py
  certbot-dns-ovh/docs/conf.py
  certbot-dns-rfc2136/docs/conf.py
  certbot-dns-route53/docs/conf.py
  certbot-dns-sakuracloud/docs/conf.py
  certbot/docs/conf.py
  letshelp-certbot/docs/conf.py
  tools/sphinx-quickstart.sh
Labels: area: code health, area: documentation

#7682 Update files from 1.1.0 release
  acme/setup.py
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/local-oldest-requirements.txt
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/local-oldest-requirements.txt
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/local-oldest-requirements.txt
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/local-oldest-requirements.txt
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/local-oldest-requirements.txt
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/local-oldest-requirements.txt
  certbot-dns-gehirn/setup.py
  certbot-dns-google/local-oldest-requirements.txt
  certbot-dns-google/setup.py
  certbot-dns-linode/local-oldest-requirements.txt
  certbot-dns-linode/setup.py
  certbot-dns-luadns/local-oldest-requirements.txt
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/local-oldest-requirements.txt
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/local-oldest-requirements.txt
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/local-oldest-requirements.txt
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/local-oldest-requirements.txt
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/local-oldest-requirements.txt
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: documentation, area: pkging

#7690 Cleanup disabled warnings list in pytest.ini
  pytest.ini
  tools/dev_constraints.txt
Labels: area: code health, area: testing

#7685 Don't run some tests multiple times
  .travis.yml
Labels: area: code health, area: testing

#7696 Include added/deleted TXT record name in RFC 2136 debug log
  certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py
Labels: area: dns

#7695 Spelling and grammar fixes
  .azure-pipelines/INSTALL.md
  acme/acme/client.py
  acme/acme/messages.py
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/certbot_apache/_internal/parser.py
  certbot-apache/tests/testdata/centos6_apache/apache/httpd/conf.d/ssl.conf
  certbot-apache/tests/testdata/centos6_apache/apache/httpd/conf/httpd.conf
  certbot-apache/tests/testdata/centos7_apache/apache/httpd/conf.d/ssl.conf
  certbot-apache/tests/testdata/debian_apache_2_4/augeas_vhosts/apache2/mods-available/ssl.conf
  certbot-apache/tests/testdata/debian_apache_2_4/default_vhost/apache2/mods-available/ssl.conf
  certbot-apache/tests/testdata/debian_apache_2_4/multiple_vhosts/apache2/mods-available/ssl.conf
  certbot-apache/tests/testdata/gentoo_apache/apache/apache2/modules.d/00_languages.conf
  certbot-apache/tests/testdata/gentoo_apache/apache/apache2/modules.d/40_mod_ssl.conf
  certbot-ci/certbot_integration_tests/conftest.py
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-compatibility-test/certbot_compatibility_test/validator_test.py
  certbot-dns-gehirn/README.rst
  certbot-dns-gehirn/certbot_dns_gehirn/__init__.py
  certbot-dns-gehirn/certbot_dns_gehirn/_internal/dns_gehirn.py
  certbot-dns-gehirn/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli.py
  certbot/certbot/_internal/ocsp.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/compat/filesystem.py
  certbot/certbot/display/ops.py
  certbot/docs/cli-help.txt
  certbot/tests/util_test.py
  letsencrypt-auto-source/rebuild_dependencies.py
  letsencrypt-auto-source/tests/centos6_tests.sh
  linter_plugin.py
  pytest.ini
Labels: area: code health, area: documentation

#7702 Downgrade NSIS and upgrade Python
  .azure-pipelines/templates/installer-tests.yml
  windows-installer/construct.py
Labels: area: testing, area: windows

#7697 Minor release script improvements
  tools/_release.sh
Labels: area: error handling, area: pkging

#7704 Don't run Python 3.5 tests twice
  .travis.yml
Labels: area: code health, area: testing

#7705 Unpin macOS image
  .travis.yml
Labels: area: code health, area: macOS, area: testing

#7721 Drop Python 3.4 support
  acme/setup.py
  certbot-apache/setup.py
  certbot-ci/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/main.py
  certbot/setup.py
  letshelp-certbot/setup.py
Labels: area: code health, area: pkging

#7712 Disable old SSL versions and ciphersuites to follow Mozilla recommendations in Apache
  certbot-apache/certbot_apache/_internal/centos-options-ssl-apache.conf
  certbot-apache/certbot_apache/_internal/constants.py
  certbot-apache/certbot_apache/_internal/options-ssl-apache.conf
  certbot/CHANGELOG.md
Labels: area: apache, area: security

#7709 Unpin Python 3.4 dependencies
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
  letsencrypt-auto-source/rebuild_dependencies.py
  tools/dev_constraints.txt
Labels: area: certbot-auto, area: code health, area: pkging

#7723 Update pinned dns-lexicon version
  tools/dev_constraints.txt
Labels: area: code health, area: dns, area: docker, area: pkging

#7611 Add backwards compatibility docs
  certbot/docs/compatibility.rst
  certbot/docs/index.rst
Labels: area: documentation

#7726 Remove SSLCompression off line from all config options
  certbot-apache/MANIFEST.in
  certbot-apache/certbot_apache/_internal/centos-options-ssl-apache.conf
  certbot-apache/certbot_apache/_internal/options-ssl-apache.conf
  certbot-apache/certbot_apache/_internal/override_centos.py
  certbot-apache/certbot_apache/_internal/override_fedora.py
  certbot/CHANGELOG.md
Labels: area: apache, area: security

#7605 Update instructions about how to build docs
  certbot/docs/contributing.rst
Labels: area: documentation

#7733 Turn off Travis notifications in test branches
  .travis.yml
Labels: area: code health, area: testing
