Repository certbot/certbot, pull requests merged in 2020-11, with the labels that each got.

#8426 Remove python_version setting from mypy.ini
  acme/acme/client.py
  acme/acme/magic_typing.py
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/tests/configurator_test.py
  certbot-compatibility-test/certbot_compatibility_test/configurators/common.py
  certbot-compatibility-test/certbot_compatibility_test/validator.py
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot/certbot/_internal/lock.py
  certbot/certbot/_internal/plugins/disco.py
  certbot/certbot/_internal/reporter.py
  certbot/certbot/crypto_util.py
  certbot/certbot/plugins/common.py
  certbot/certbot/util.py
  mypy.ini
Labels: area: code health, area: mypy, area: testing

#8401 Write a replacement for pipstrap
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/steps/tox-steps.yml
  tests/letstest/scripts/test_sdists.sh
  tools/_venv_common.py
  tools/docker/core/Dockerfile
  tools/docker/plugin/Dockerfile
  tools/oldest_constraints.txt
  tools/pip_install.py
  tools/pipstrap.py
  tools/run_oldest_tests.sh
  tox.ini
  windows-installer/construct.py
Labels: area: python, area: tooling, priority: significant

#8432 certbot.display: add new method to print CLI messages
  certbot/certbot/_internal/log.py
  certbot/certbot/_internal/main.py
  certbot/certbot/display/util.py
  certbot/tests/display/util_test.py
  certbot/tests/main_test.py
Labels: area: ui / ux

#8436 cli: miscellaneous IReporter removals
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot/certbot/_internal/cert_manager.py
  certbot/certbot/_internal/eff.py
  certbot/certbot/_internal/main.py
  certbot/certbot/display/ops.py
  certbot/tests/cert_manager_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/eff_test.py
  certbot/tests/main_test.py
Labels: area: ui / ux

#8435 Handle unexpected key type migration.
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot/certbot/_internal/main.py
  certbot/tests/main_test.py
Labels: area: cert management, area: error handling, area: ui / ux

#8438 Close the session once snap connections are acquired
  certbot/certbot/_internal/snap_config.py
Labels: area: code health

#8447 Add certbot renew --key-type test
  certbot-ci/certbot_integration_tests/certbot_tests/assertions.py
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
Labels: area: testing

#8449 Use Python 3.8 for Linux integration tests
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
Labels: area: code health, area: testing

#7722 Add --dns-server option in run_acme_server
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot/docs/contributing.rst
Labels: area: boulder, area: testing

#8395 cli: improve Obtaining/Renewing wording
  certbot/certbot/_internal/main.py
  certbot/certbot/display/util.py
  certbot/tests/display/util_test.py
Labels: area: ui / ux

#8448 Add certbot-dns-rfc2136 integration testing
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  certbot-ci/certbot_integration_tests/assets/bind-config/conf/named.conf
  certbot-ci/certbot_integration_tests/assets/bind-config/rfc2136-credentials-default.ini.tpl
  certbot-ci/certbot_integration_tests/assets/bind-config/zones/db.example.com
  certbot-ci/certbot_integration_tests/assets/bind-config/zones/db.sub.example.com
  certbot-ci/certbot_integration_tests/assets/bind-config/zones/rpz.mock-recursion
  certbot-ci/certbot_integration_tests/conftest.py
  certbot-ci/certbot_integration_tests/rfc2136_tests/__init__.py
  certbot-ci/certbot_integration_tests/rfc2136_tests/context.py
  certbot-ci/certbot_integration_tests/rfc2136_tests/test_main.py
  certbot-ci/certbot_integration_tests/utils/dns_server.py
  tox.ini
Labels: area: dns, area: testing

#8458 Fix Python 2 integration tests
  certbot-ci/certbot_integration_tests/utils/dns_server.py
Labels: area: code health, area: python, area: testing

#8371 Read files as binary in crypto_util for crypto.load_certificate.
  certbot/certbot/crypto_util.py
Labels: bug

#8464 Flesh out ECDSA documentation
  certbot/CHANGELOG.md
  certbot/docs/using.rst
Labels: area: documentation, area: security, priority: significant

#8460 Add Python 3.9 support and tests
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  acme/setup.py
  certbot-apache/setup.py
  certbot-ci/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/setup.py
  tools/dev_constraints.txt
  tools/merge_requirements.py
Labels: area: pkging, area: python, priority: significant

#8480 nginx: fix Unicode crash on Python 2
  certbot-ci/certbot_integration_tests/nginx_tests/nginx_config.py
  certbot-nginx/certbot_nginx/_internal/http_01.py
  certbot-nginx/certbot_nginx/_internal/nginxparser.py
  certbot-nginx/certbot_nginx/_internal/parser.py
  certbot-nginx/tests/parser_test.py
  certbot/CHANGELOG.md
Labels: area: encoding/type error, area: nginx
