Repository certbot/certbot, pull requests merged in 2020-04, with the labels that each got.

#7388 acme: socket timeout for HTTP standalone servers
  acme/acme/standalone.py
  acme/tests/standalone_test.py
  certbot/CHANGELOG.md
Labels: priority: unplanned

#7885 Print boulder logs when boulder setup fails
  certbot-ci/certbot_integration_tests/utils/acme_server.py
Labels: area: error handling, area: testing

#7876 Upgrade the test farm tests to use Python 3
  .gitignore
  .travis.yml
  tests/letstest/README.md
  tests/letstest/multitester.py
  tests/letstest/requirements.txt
Labels: area: code health, area: testing, area: tooling

#7891 Minor bugfixes
  acme/acme/client.py
  acme/docs/conf.py
  acme/tests/errors_test.py
  certbot-apache/certbot_apache/_internal/apache_util.py
  certbot-apache/certbot_apache/_internal/assertions.py
  certbot-apache/certbot_apache/_internal/augeasparser.py
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/certbot_apache/_internal/display_ops.py
  certbot-apache/certbot_apache/_internal/dualparser.py
  certbot-apache/certbot_apache/_internal/parser.py
  certbot-apache/certbot_apache/_internal/parsernode_util.py
  certbot-apache/tests/augeasnode_test.py
  certbot-apache/tests/centos6_test.py
  certbot-apache/tests/centos_test.py
  certbot-apache/tests/configurator_test.py
  certbot-apache/tests/display_ops_test.py
  certbot-apache/tests/gentoo_test.py
  certbot-apache/tests/obj_test.py
  certbot-apache/tests/util.py
  certbot-ci/certbot_integration_tests/certbot_tests/context.py
  certbot-ci/certbot_integration_tests/utils/misc.py
  certbot-compatibility-test/certbot_compatibility_test/test_driver.py
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot-nginx/certbot_nginx/_internal/display_ops.py
  certbot-nginx/certbot_nginx/_internal/parser.py
  certbot-nginx/certbot_nginx/_internal/parser_obj.py
  certbot-nginx/tests/configurator_test.py
  certbot-nginx/tests/obj_test.py
  certbot-nginx/tests/parser_obj_test.py
  certbot-nginx/tests/parser_test.py
  certbot/certbot/_internal/cli/cli_constants.py
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/plugins/manual.py
  certbot/certbot/_internal/plugins/selection.py
  certbot/certbot/display/ops.py
  certbot/certbot/plugins/storage.py
  certbot/tests/display/ops_test.py
  certbot/tests/display/util_test.py
  certbot/tests/error_handler_test.py
  certbot/tests/hook_test.py
  certbot/tests/main_test.py
  certbot/tests/plugins/common_test.py
  certbot/tests/plugins/standalone_test.py
  certbot/tests/reverter_test.py
  letsencrypt-auto-source/rebuild_dependencies.py
  tools/_venv_common.py
  tools/deactivate.py
  windows-installer/construct.py
Labels: area: code health

#7894 Do not require mock in Python 3 in acme module
  acme/setup.py
  acme/tests/challenges_test.py
  acme/tests/client_test.py
  acme/tests/errors_test.py
  acme/tests/magic_typing_test.py
  acme/tests/messages_test.py
  acme/tests/standalone_test.py
Labels: area: code health, area: pkging, area: testing, priority: high

#7895 Do not require mock in Python 3 in certbot module
  certbot/certbot/plugins/dns_test_common.py
  certbot/certbot/plugins/dns_test_common_lexicon.py
  certbot/certbot/tests/util.py
  certbot/setup.py
  certbot/tests/account_test.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/cli_test.py
  certbot/tests/client_test.py
  certbot/tests/compat/filesystem_test.py
  certbot/tests/configuration_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/display/completer_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/display/util_test.py
  certbot/tests/eff_test.py
  certbot/tests/error_handler_test.py
  certbot/tests/errors_test.py
  certbot/tests/hook_test.py
  certbot/tests/lock_test.py
  certbot/tests/log_test.py
  certbot/tests/main_test.py
  certbot/tests/ocsp_test.py
  certbot/tests/plugins/common_test.py
  certbot/tests/plugins/disco_test.py
  certbot/tests/plugins/dns_common_lexicon_test.py
  certbot/tests/plugins/dns_common_test.py
  certbot/tests/plugins/enhancements_test.py
  certbot/tests/plugins/manual_test.py
  certbot/tests/plugins/null_test.py
  certbot/tests/plugins/selection_test.py
  certbot/tests/plugins/standalone_test.py
  certbot/tests/plugins/storage_test.py
  certbot/tests/plugins/util_test.py
  certbot/tests/plugins/webroot_test.py
  certbot/tests/renewal_test.py
  certbot/tests/renewupdater_test.py
  certbot/tests/reporter_test.py
  certbot/tests/reverter_test.py
  certbot/tests/storage_test.py
  certbot/tests/util_test.py
Labels: area: code health, area: pkging, area: testing, priority: high

#7906 Remove Ubuntu 19.04 tests
  tests/letstest/apache2_targets.yaml
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#7910 Do not require mock in Python 3 in acme module
  acme/setup.py
  acme/tests/challenges_test.py
  acme/tests/client_test.py
  acme/tests/errors_test.py
  acme/tests/magic_typing_test.py
  acme/tests/messages_test.py
  acme/tests/standalone_test.py
Labels: area: code health, area: pkging, area: testing, priority: high

#7911 Do not require mock in Python 3 in certbot module
  certbot/certbot/plugins/dns_test_common.py
  certbot/certbot/plugins/dns_test_common_lexicon.py
  certbot/certbot/tests/util.py
  certbot/setup.py
  certbot/tests/account_test.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/cli_test.py
  certbot/tests/client_test.py
  certbot/tests/compat/filesystem_test.py
  certbot/tests/configuration_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/display/completer_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/display/util_test.py
  certbot/tests/eff_test.py
  certbot/tests/error_handler_test.py
  certbot/tests/errors_test.py
  certbot/tests/hook_test.py
  certbot/tests/lock_test.py
  certbot/tests/log_test.py
  certbot/tests/main_test.py
  certbot/tests/ocsp_test.py
  certbot/tests/plugins/common_test.py
  certbot/tests/plugins/disco_test.py
  certbot/tests/plugins/dns_common_lexicon_test.py
  certbot/tests/plugins/dns_common_test.py
  certbot/tests/plugins/enhancements_test.py
  certbot/tests/plugins/manual_test.py
  certbot/tests/plugins/null_test.py
  certbot/tests/plugins/selection_test.py
  certbot/tests/plugins/standalone_test.py
  certbot/tests/plugins/storage_test.py
  certbot/tests/plugins/util_test.py
  certbot/tests/plugins/webroot_test.py
  certbot/tests/renewal_test.py
  certbot/tests/renewupdater_test.py
  certbot/tests/reporter_test.py
  certbot/tests/reverter_test.py
  certbot/tests/storage_test.py
  certbot/tests/util_test.py
Labels: area: code health, area: pkging, area: testing, priority: high

#7896 Do not require mock in Python 3 in apache module
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot-apache/tests/augeasnode_test.py
  certbot-apache/tests/autohsts_test.py
  certbot-apache/tests/centos_test.py
  certbot-apache/tests/configurator_reverter_test.py
  certbot-apache/tests/configurator_test.py
  certbot-apache/tests/debian_test.py
  certbot-apache/tests/display_ops_test.py
  certbot-apache/tests/dualnode_test.py
  certbot-apache/tests/entrypoint_test.py
  certbot-apache/tests/fedora_test.py
  certbot-apache/tests/gentoo_test.py
  certbot-apache/tests/http_01_test.py
  certbot-apache/tests/parser_test.py
  certbot-apache/tests/parsernode_configurator_test.py
  certbot-apache/tests/util.py
Labels: area: code health, area: pkging, area: testing, priority: high

#7898 Do not require mock in Python 3 in nginx module
  certbot-nginx/setup.py
  certbot-nginx/tests/configurator_test.py
  certbot-nginx/tests/http_01_test.py
  certbot-nginx/tests/parser_obj_test.py
  certbot-nginx/tests/test_util.py
Labels: area: code health, area: pkging, area: testing, priority: high

#7899 Do not require mock in Python 3 in certbot-compatibility-test module
  certbot-compatibility-test/certbot_compatibility_test/configurators/apache/common.py
  certbot-compatibility-test/certbot_compatibility_test/validator_test.py
  certbot-compatibility-test/setup.py
Labels: area: code health, area: pkging, area: testing, priority: high

#7900 Do not require mock in Python 3 in certbot-dns modules
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudflare/tests/dns_cloudflare_test.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-cloudxns/tests/dns_cloudxns_test.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-digitalocean/tests/dns_digitalocean_test.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsimple/tests/dns_dnsimple_test.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-dnsmadeeasy/tests/dns_dnsmadeeasy_test.py
  certbot-dns-gehirn/setup.py
  certbot-dns-gehirn/tests/dns_gehirn_test.py
  certbot-dns-google/setup.py
  certbot-dns-google/tests/dns_google_test.py
  certbot-dns-linode/setup.py
  certbot-dns-linode/tests/dns_linode_test.py
  certbot-dns-luadns/setup.py
  certbot-dns-luadns/tests/dns_luadns_test.py
  certbot-dns-nsone/setup.py
  certbot-dns-nsone/tests/dns_nsone_test.py
  certbot-dns-ovh/setup.py
  certbot-dns-ovh/tests/dns_ovh_test.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-rfc2136/tests/dns_rfc2136_test.py
  certbot-dns-route53/setup.py
  certbot-dns-route53/tests/dns_route53_test.py
  certbot-dns-sakuracloud/setup.py
  certbot-dns-sakuracloud/tests/dns_sakuracloud_test.py
  certbot/CHANGELOG.md
Labels: area: code health, area: pkging, area: testing, priority: high

#7905 Consolidate cover envs and default to py3-cover
  .travis.yml
  certbot-apache/certbot_apache/_internal/parser.py
  tox.ini
Labels: area: code health, area: testing

#7918 Use Python 3 in the release script
  tools/_release.sh
Labels: area: pkging, area: tooling

#7919 Update rate limits url
  certbot/docs/using.rst
Labels: area: documentation

#7916 Test on Ubuntu 19.10
  tests/letstest/apache2_targets.yaml
  tests/letstest/targets.yaml
Labels: area: debian / ubuntu, area: testing

#7917 Test on fedora 31
  tests/letstest/apache2_targets.yaml
  tests/letstest/targets.yaml
Labels: area: fedora / redhat / CentOS, area: testing

#7914 Update dev docs to reflect Python 2 EOL
  certbot/docs/contributing.rst
Labels: area: documentation, area: testing

#7927 Fix Travis extended/full test suite logic
  .travis.yml
Labels: area: testing

#7889 Add snap instructions
  certbot/docs/install.rst
Labels: area: documentation, area: snaps, blocked

#7920 Remove useless before_install lines
  .travis.yml
Labels: area: code health, area: testing

#7926 Deprecate certbot-auto on Gentoo, macOS, and FreeBSD
  certbot/CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
Labels: area: certbot-auto

#7937 Add --chain-path to --help install output.
  certbot/certbot/_internal/cli/paths_parser.py
Labels: area: documentation, area: install

#7936 Don't tell people to use venv.py
  certbot/docs/contributing.rst
Labels: area: documentation, area: testing

#7923 Avoid deleting the workspace twice
  certbot-ci/certbot_integration_tests/utils/acme_server.py
Labels: area: error handling, area: testing, area: ui / ux

#7948 Squashed snap build
  .gitignore
  .travis.yml
  snap/local/build_and_install.sh
  snap/snapcraft.yaml
  tox.ini
Labels: area: pkging, area: snaps

#7800 Run hooks with Powershell on Windows
  certbot-ci/certbot_integration_tests/assets/hook.py
  certbot-ci/certbot_integration_tests/certbot_tests/assertions.py
  certbot-ci/certbot_integration_tests/utils/misc.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/hooks.py
  certbot/certbot/_internal/plugins/manual.py
  certbot/certbot/compat/misc.py
  certbot/tests/compat/misc_test.py
  certbot/tests/hook_test.py
Labels: area: hooks, area: testing, area: windows
