Repository certbot/certbot, pull requests merged in 2020-02, with the labels that each got.

#7729 Fix a typo in Nginx
  certbot-nginx/certbot_nginx/_internal/configurator.py
Labels: area: nginx, area: ui / ux

#7746 Set recreate = true in tox.ini
  tox.ini
Labels: area: code health, area: testing

#7748 Add triggers for only a single CI system
  .azure-pipelines/advanced.yml
  .travis.yml
  certbot/docs/contributing.rst
Labels: area: code health, area: testing

#7753 Don't display todo comments in docs
  acme/docs/conf.py
  certbot-dns-cloudflare/docs/conf.py
  certbot-dns-cloudxns/docs/conf.py
  certbot-dns-digitalocean/docs/conf.py
  certbot-dns-dnsimple/docs/conf.py
  certbot-dns-dnsmadeeasy/docs/conf.py
  certbot-dns-gehirn/docs/conf.py
  certbot-dns-google/docs/conf.py
  certbot-dns-linode/docs/conf.py
  certbot-dns-luadns/docs/conf.py
  certbot-dns-nsone/docs/conf.py
  certbot-dns-ovh/docs/conf.py
  certbot-dns-rfc2136/docs/conf.py
  certbot-dns-route53/docs/conf.py
  certbot-dns-sakuracloud/docs/conf.py
  certbot/docs/conf.py
  letshelp-certbot/docs/conf.py
  tools/sphinx-quickstart.sh
Labels: area: documentation

#7754 Remove text that certbot.tests.utils isn't public
  certbot/certbot/tests/util.py
Labels: area: documentation

#7757 Remove link to letsencrypt readthedocs
  certbot/README.rst
Labels: area: documentation

#7759 Print script output in case of a failure
  letsencrypt-auto-source/tests/auto_test.py
Labels: area: code health, area: testing

#7760 Fix unpinned tests
  .travis.yml
Labels: area: code health, area: testing

#7766 Clarify the minimum pyparsing version
  certbot-nginx/setup.py
  tools/oldest_constraints.txt
Labels: area: code health, area: nginx, area: testing

#7763 More robustly stop patches
  certbot/tests/cert_manager_test.py
  certbot/tests/main_test.py
Labels: area: code health, area: testing

#7761 Remove letshelp-certbot
  certbot/docs/packaging.rst
  letshelp-certbot/LICENSE.txt
  letshelp-certbot/MANIFEST.in
  letshelp-certbot/README.rst
  letshelp-certbot/docs/.gitignore
  letshelp-certbot/docs/Makefile
  letshelp-certbot/docs/_static/.gitignore
  letshelp-certbot/docs/_templates/.gitignore
  letshelp-certbot/docs/api.rst
  letshelp-certbot/docs/api/index.rst
  letshelp-certbot/docs/conf.py
  letshelp-certbot/docs/index.rst
  letshelp-certbot/docs/make.bat
  letshelp-certbot/letshelp_certbot/__init__.py
  letshelp-certbot/letshelp_certbot/apache.py
  letshelp-certbot/letshelp_certbot/apache_test.py
  letshelp-certbot/letshelp_certbot/magic_typing.py
  letshelp-certbot/letshelp_certbot/magic_typing_test.py
  letshelp-certbot/letshelp_certbot/testdata/mods-available/ssl.load
  letshelp-certbot/letshelp_certbot/testdata/mods-enabled/ssl.load
  letshelp-certbot/letshelp_certbot/testdata/super_secret_file.txt
  letshelp-certbot/letshelp_certbot/testdata/uncommonly_named_k3y
  letshelp-certbot/letshelp_certbot/testdata/uncommonly_named_p4sswd
  letshelp-certbot/readthedocs.org.requirements.txt
  letshelp-certbot/setup.cfg
  letshelp-certbot/setup.py
  linter_plugin.py
  mypy.ini
  tools/_venv_common.py
  tools/install_and_test.py
  tox.cover.py
  tox.ini
Labels: area: code health

#7780 Fixes pylint failures in some Python versions
  acme/acme/challenges.py
  acme/acme/jws.py
Labels: area: code health, area: testing

#7767 Correct AutoHSTS docs
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot/certbot/plugins/enhancements.py
Labels: area: code health, area: documentation

#7765 Add docs about our PGP key
  certbot/docs/packaging.rst
Labels: area: documentation, area: security

#7793 Move our macOS tests to Azure Pipelines
  .azure-pipelines/templates/tests-suite.yml
  .travis.yml
Labels: area: macOS, area: testing

#6803 Refactor cli.py, splitting in it smaller submodules
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli.py
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/_internal/cli/cli_constants.py
  certbot/certbot/_internal/cli/cli_utils.py
  certbot/certbot/_internal/cli/group_adder.py
  certbot/certbot/_internal/cli/helpful.py
  certbot/certbot/_internal/cli/paths_parser.py
  certbot/certbot/_internal/cli/plugins_parsing.py
  certbot/certbot/_internal/cli/report_config_interaction.py
  certbot/certbot/_internal/cli/subparsers.py
  certbot/certbot/_internal/cli/verb_help.py
  certbot/tests/cli_test.py
  certbot/tests/helpful_test.py
Labels: area: code health, area: refactoring, area: testing, current sprint

#7342 acme: ignore params in content-type check
  acme/acme/client.py
  acme/tests/client_test.py
  certbot/CHANGELOG.md
Labels: area: acme, area: logging

#7568 Fix issue #7165 in _create_challenge_dirs(), attempt to fix pylint errors
  certbot/CHANGELOG.md
  certbot/certbot/_internal/plugins/webroot.py
Labels: priority: normal

#7801 remove _internal docs
  certbot/CHANGELOG.md
Labels: area: documentation

#7813 Split advanced pipeline
  .azure-pipelines/advanced-test.yml
  .azure-pipelines/advanced.yml
  .azure-pipelines/release.yml
Labels: area: testing

#7809 Update test farm dependencies
  tests/letstest/requirements.txt
Labels: area: macOS, area: travis-test-farm-test

#7805 Remove unused notify code.
  certbot/certbot/_internal/notify.py
  certbot/tests/notify_test.py
Labels: area: code health

#7804 Fix mypy on macOS
  certbot/certbot/util.py
Labels: area: macOS, area: mypy, area: testing

#7794 Fix tests on macOS Catalina
  certbot/tests/cli_test.py
Labels: area: macOS, area: testing

#7541 Fix docstring
  certbot/tests/plugins/common_test.py
Labels: area: code health, area: documentation

#7509 Remove references to deprecated flags in Certbot
  certbot/certbot/_internal/main.py
  certbot/certbot/display/ops.py
  certbot/tests/cli_test.py
Labels: area: code health

#7820 Don't run advanced tests on PRs
  .azure-pipelines/advanced-test.yml
  .azure-pipelines/advanced.yml
Labels: area: testing
