Repository certbot/certbot, pull requests merged in 2020-06, with the labels that each got.

#8035 Keep Certbot working on non-EOL'd non-x86_64 systems
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
Labels: area: certbot-auto, area: pkging

#8039 Make rebuild_dependencies.py executable
  letsencrypt-auto-source/rebuild_dependencies.py
Labels: area: certbot-auto

#8040 Release 1.5.0
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#8036 Upgrade Certbot dependencies
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/dependency-requirements.txt
  letsencrypt-auto-source/rebuild_dependencies.py
Labels: area: pkging, priority: high

#8033 Add support for NetBSD
  certbot-nginx/certbot_nginx/_internal/constants.py
  certbot/CHANGELOG.md
Labels: area: nginx, area: pkging, priority: unplanned

#8044 Add comment about cryptography's use of tools script
  tools/pip_install_editable.py
Labels: area: documentation, area: tooling

#8063 Stop running snapcraft with sudo
  snap/local/build_and_install.sh
Labels: area: snaps, area: testing

#7967 Implement umask for Windows
  certbot-apache/certbot_apache/_internal/http_01.py
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/plugins/webroot.py
  certbot/certbot/compat/filesystem.py
  certbot/certbot/compat/os.py
  certbot/tests/compat/filesystem_test.py
Labels: area: security, area: security enhancements, area: windows

#8066 Fix typo
  certbot/docs/contributing.rst
Labels: area: documentation

#8067 Add changelog entry about snap architectures
  certbot/CHANGELOG.md
Labels: area: documentation, area: snaps

#8077 Remove on_cancel which isn't recognized by Travis
  .travis.yml
Labels: area: code health, area: testing

#8083 Drop i386 architecture on snap build
  .travis.yml
  certbot/CHANGELOG.md
  snap/local/common.sh
  snap/local/compile_native_wheels.sh
  snap/local/packages/cffi/cffi-1.14.0-cp36-cp36m-manylinux1_i686.whl
  snap/local/packages/cryptography/cryptography-2.8-cp36-cp36m-linux_i686.whl
Labels: area: snaps

#8084 Remove the need for TRAVIS to be set.
  snap/local/build_and_install.sh
Labels: area: snaps

#8086 Upgrade snap to be based on core20
  snap/local/build_and_install.sh
  snap/local/compile_native_wheels.sh
  snap/local/packages/cffi/cffi-1.14.0-cp36-cp36m-linux_aarch64.whl
  snap/local/packages/cffi/cffi-1.14.0-cp36-cp36m-linux_armv7l.whl
  snap/local/packages/cffi/cffi-1.14.0-cp38-cp38-linux_aarch64.whl
  snap/local/packages/cffi/cffi-1.14.0-cp38-cp38-linux_armv7l.whl
  snap/local/packages/cryptography/cryptography-2.8-cp36-cp36m-linux_aarch64.whl
  snap/local/packages/cryptography/cryptography-2.8-cp36-cp36m-linux_armv7l.whl
  snap/local/packages/cryptography/cryptography-2.8-cp38-cp38-linux_aarch64.whl
  snap/local/packages/cryptography/cryptography-2.8-cp38-cp38-linux_armv7l.whl
  snap/snapcraft.yaml
Labels: area: snaps

#8089 Merge the snap-plugin branch into master
  certbot-dns-dnsimple/snap/snapcraft.yaml
  snap/local/README.md
Labels: area: code health, area: documentation, area: snaps

#8076 Deferred EFF subscription until the first certificate is successfully issued
  certbot/certbot/_internal/account.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/eff.py
  certbot/certbot/_internal/main.py
  certbot/tests/account_test.py
  certbot/tests/client_test.py
  certbot/tests/eff_test.py
  certbot/tests/main_test.py
Labels: area: ui / ux

#8095 Use certbot.wrapper during renewal.
  snap/snapcraft.yaml
Labels: area: renewal, area: snaps

#8094 Do not unstage generated cffi augeas
  snap/snapcraft.yaml
Labels: area: apache, area: code health, area: snaps

#8097 Build the constraints file insided snapcraft
  snap/local/build_and_install.sh
  snap/snapcraft.yaml
Labels: area: snaps

#8101 Remove snap-plugin reference from README
  snap/local/README.md
Labels: area: documentation, area: snaps

#8102 Remove unneeded step to create constraints file
  snap/local/README.md
Labels: area: documentation, area: snaps

#8104 Correct plugin constraints
  snap/local/README.md
Labels: area: code health, area: dns, area: pkging, area: snaps

#8061 Generalize renewal rate limit UI warning message (#3456)
  certbot/CHANGELOG.md
  certbot/certbot/_internal/main.py
Labels: area: code health, area: spec-compliance, area: ui / ux

#8113 Add awscli to requirements.txt
  tests/letstest/requirements.txt
Labels: area: documentation

#8116 Add missing spaces to manual plugin help
  certbot/certbot/_internal/plugins/manual.py
Labels: area: documentation, area: manual authenticator
