Repository certbot/certbot, pull requests merged in 2020-07, with the labels that each got.

#8080 certbot: add --preferred-chain
  acme/acme/client.py
  acme/acme/messages.py
  acme/tests/client_test.py
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-ci/certbot_integration_tests/utils/constants.py
  certbot-ci/certbot_integration_tests/utils/misc.py
  certbot-nginx/local-oldest-requirements.txt
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/constants.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/crypto_util.py
  certbot/certbot/interfaces.py
  certbot/certbot/tests/testdata/cert_intermediate_1.pem
  certbot/certbot/tests/testdata/cert_intermediate_2.pem
  certbot/certbot/tests/testdata/cert_leaf.pem
  certbot/local-oldest-requirements.txt
  certbot/setup.py
  certbot/tests/client_test.py
  certbot/tests/crypto_util_test.py
Labels: area: acme, area: cert management, priority: high

#8098 Migrate the CI pipeline from Travis to Azure Pipeline
  .azure-pipelines/advanced-test.yml
  .azure-pipelines/advanced.yml
  .azure-pipelines/main.yml
  .azure-pipelines/nightly.yml
  .azure-pipelines/release.yml
  .azure-pipelines/templates/changelog.yml
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  .azure-pipelines/templates/stages/changelog-stage.yml
  .azure-pipelines/templates/stages/deploy-stage.yml
  .azure-pipelines/templates/stages/notify-failure-stage.yml
  .azure-pipelines/templates/stages/test-and-package-stage.yml
  .azure-pipelines/templates/steps/tox-steps.yml
  .azure-pipelines/templates/tests-suite.yml
  .travis.yml
  acme/setup.py
  certbot/README.rst
  certbot/docs/contributing.rst
  snap/local/build.sh
  tests/letstest/multitester.py
  tests/letstest/travis-setup.sh
  tests/letstest/travis-test-farm.pem.enc
  tests/lock_test.py
  tests/modification-check.py
  tools/oldest_constraints.txt
  tools/run_oldest_tests.sh
  tox.ini
Labels: area: code health, area: testing

#8126 Do not build pushes to master
  .azure-pipelines/main.yml
Labels: area: performance, area: testing

#8127 Switch build status to nightly pipeline
  certbot/README.rst
Labels: area: documentation, area: testing

#8133 Run at 4:30 UTC to have Azure reparse YAML file
  .azure-pipelines/nightly.yml
Labels: area: testing

#8128 Remove grade devel from Certbot snap
  snap/snapcraft.yaml
Labels: area: pkging, area: snaps

#8135 Remove unnecessary symlink
  .azure-pipelines/templates/steps/tox-steps.yml
Labels: area: code health, area: testing

#8132 Some improvements on snap builds
  snap/local/build.sh
  tools/simple_http_server.py
Labels: area: pkging

#8136 Update files from 1.6.0 release
  acme/setup.py
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  certbot/local-oldest-requirements.txt
  certbot/setup.py
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: documentation, area: pkging

#8137 Use snapcraft upload, not snapcraft push
  .azure-pipelines/templates/stages/deploy-stage.yml
Labels: area: code health, area: pkging, area: snaps

#8129 Build the DNS plugins snaps
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/stages/deploy-stage.yml
  certbot-ci/snap_integration_tests/__init__.py
  certbot-ci/snap_integration_tests/conftest.py
  certbot-ci/snap_integration_tests/dns_tests/__init__.py
  certbot-ci/snap_integration_tests/dns_tests/test_main.py
  tools/snap/README.md
  tools/snap/build.sh
  tools/snap/build_dns.sh
  tools/snap/common.sh
  tools/snap/compile_native_wheels.sh
  tools/snap/packages/cffi/cffi-1.14.0-cp38-cp38-linux_aarch64.whl
  tools/snap/packages/cffi/cffi-1.14.0-cp38-cp38-linux_armv7l.whl
  tools/snap/packages/cryptography/cryptography-2.8-cp38-cp38-linux_aarch64.whl
  tools/snap/packages/cryptography/cryptography-2.8-cp38-cp38-linux_armv7l.whl
Labels: area: dns, area: install, area: pkging, area: snaps, area: testing

#8131 Use 3rd party plugins without prefix + set a deprecation path for the prefixed version
  certbot/CHANGELOG.md
  certbot/certbot/_internal/plugins/disco.py
  certbot/certbot/_internal/plugins/selection.py
  certbot/tests/plugins/disco_test.py
  certbot/tests/plugins/selection_test.py
Labels: area: 3rd party, area: pkging

#8115 added inwx plugin
  certbot/docs/using.rst
Labels: area: dns, area: documentation

#8147 Specify the Certbot snap grade
  snap/snapcraft.yaml
Labels: area: code health, area: snaps

#8152 Update to IPython with Python 3.8 support
  certbot/setup.py
  tools/dev_constraints.txt
  tools/oldest_constraints.txt
Labels: area: code health, area: testing, area: tooling

#8159 Do not create the symlink for test assets on Windows if the asset pat…
  certbot-ci/certbot_integration_tests/utils/misc.py
Labels: area: testing, area: windows

#8158 Use a specific tag of adferrand/snapcraft to build QEMU snaps and avoid failures
  tools/snap/build.sh
  tools/snap/build_dns.sh
Labels: area: snaps

#8154 Add warnings about Python 3.5 deprecation in Certbot
  acme/acme/__init__.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/certbot/_internal/main.py
Labels: area: code health

#8153 Build snaps using the remote-build feature
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/stages/deploy-stage.yml
  certbot-ci/snap_integration_tests/conftest.py
  certbot-ci/snap_integration_tests/dns_tests/test_main.py
  certbot-dns-cloudflare/snap/snapcraft.yaml
  certbot-dns-cloudxns/snap/snapcraft.yaml
  certbot-dns-digitalocean/snap/snapcraft.yaml
  certbot-dns-dnsimple/snap/snapcraft.yaml
  certbot-dns-dnsmadeeasy/snap/snapcraft.yaml
  certbot-dns-gehirn/snap/snapcraft.yaml
  certbot-dns-google/snap/snapcraft.yaml
  certbot-dns-linode/snap/snapcraft.yaml
  certbot-dns-luadns/snap/snapcraft.yaml
  certbot-dns-nsone/snap/snapcraft.yaml
  certbot-dns-ovh/snap/snapcraft.yaml
  certbot-dns-rfc2136/snap/snapcraft.yaml
  certbot-dns-route53/snap/snapcraft.yaml
  certbot-dns-sakuracloud/snap/snapcraft.yaml
  snap/snapcraft.yaml
  tools/snap/build_remote.py
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: pkging, area: snaps, area: testing, area: tooling

#8145 Make externally snapped plugin updates more stable
  certbot-ci/snap_integration_tests/dns_tests/test_main.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudflare/snap/hooks/post-refresh
  certbot-dns-cloudflare/snap/snapcraft.yaml
  certbot-dns-cloudxns/setup.py
  certbot-dns-cloudxns/snap/hooks/post-refresh
  certbot-dns-cloudxns/snap/snapcraft.yaml
  certbot-dns-digitalocean/setup.py
  certbot-dns-digitalocean/snap/hooks/post-refresh
  certbot-dns-digitalocean/snap/snapcraft.yaml
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsimple/snap/hooks/post-refresh
  certbot-dns-dnsimple/snap/snapcraft.yaml
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-dnsmadeeasy/snap/hooks/post-refresh
  certbot-dns-dnsmadeeasy/snap/snapcraft.yaml
  certbot-dns-gehirn/setup.py
  certbot-dns-gehirn/snap/hooks/post-refresh
  certbot-dns-gehirn/snap/snapcraft.yaml
  certbot-dns-google/setup.py
  certbot-dns-google/snap/hooks/post-refresh
  certbot-dns-google/snap/snapcraft.yaml
  certbot-dns-linode/setup.py
  certbot-dns-linode/snap/hooks/post-refresh
  certbot-dns-linode/snap/snapcraft.yaml
  certbot-dns-luadns/setup.py
  certbot-dns-luadns/snap/hooks/post-refresh
  certbot-dns-luadns/snap/snapcraft.yaml
  certbot-dns-nsone/setup.py
  certbot-dns-nsone/snap/hooks/post-refresh
  certbot-dns-nsone/snap/snapcraft.yaml
  certbot-dns-ovh/setup.py
  certbot-dns-ovh/snap/hooks/post-refresh
  certbot-dns-ovh/snap/snapcraft.yaml
  certbot-dns-rfc2136/setup.py
  certbot-dns-rfc2136/snap/hooks/post-refresh
  certbot-dns-rfc2136/snap/snapcraft.yaml
  certbot-dns-route53/setup.py
  certbot-dns-route53/snap/hooks/post-refresh
  certbot-dns-route53/snap/snapcraft.yaml
  certbot-dns-sakuracloud/setup.py
  certbot-dns-sakuracloud/snap/hooks/post-refresh
  certbot-dns-sakuracloud/snap/snapcraft.yaml
  snap/snapcraft.yaml
  tools/snap/README.md
  tools/snap/generate_dnsplugins_postrefreshhook.sh
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: 3rd party, area: dns, area: snaps

#8167 Remove old snapcraft files
  tools/snap/build.sh
  tools/snap/build_dns.sh
  tools/snap/common.sh
  tools/snap/compile_native_wheels.sh
  tools/snap/packages/cffi/cffi-1.14.0-cp38-cp38-linux_aarch64.whl
  tools/snap/packages/cffi/cffi-1.14.0-cp38-cp38-linux_armv7l.whl
  tools/snap/packages/cryptography/cryptography-2.8-cp38-cp38-linux_aarch64.whl
  tools/snap/packages/cryptography/cryptography-2.8-cp38-cp38-linux_armv7l.whl
Labels: area: code health, area: snaps, area: tooling

#8174 Document that snaps are available for 3 architectures
  certbot/docs/install.rst
Labels: area: documentation, area: snaps

#8163 nginx: add --nginx-sleep-seconds
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot-nginx/certbot_nginx/_internal/constants.py
  certbot-nginx/tests/configurator_test.py
  certbot-nginx/tests/test_util.py
  certbot/CHANGELOG.md
Labels: area: nginx, priority: unplanned

#8178 Remove text about snap beta status
  certbot/docs/install.rst
Labels: area: documentation, area: snaps

#8185 Do not run tests on pushes to *.x for performance/sanity
  .azure-pipelines/advanced-test.yml
Labels: area: code health, area: performance, area: testing

#8183 Automatically publish snaps to the beta channel
  .azure-pipelines/release.yml
  .azure-pipelines/templates/stages/deploy-stage.yml
Labels: area: snaps, area: tooling
