Repository certbot/certbot, pull requests merged in 2020-10, with the labels that each got.

#8324 Deprecate certbot-auto outside of Debian and RHEL
  certbot/CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
Labels: area: certbot-auto, area: code health, area: pkging, priority: high

#8325 Automatically retry test farm tests
  .azure-pipelines/templates/stages/deploy-stage.yml
  tools/retry.sh
  tox.ini
Labels: area: code health, area: testing, area: tooling

#8289 Upgrade httplib2
  certbot/CHANGELOG.md
  tools/dev_constraints.txt
Labels: area: code health, area: dns

#8336 Add snap log files to gitignore
  .gitignore
Labels: area: code health, area: snaps, area: tooling

#8344 Set Certbot snap version from __init__.py
  snap/snapcraft.yaml
Labels: area: code health, area: documentation, area: pkging, area: snaps, area: tooling

#8343 Reuse key renewal params
  certbot/certbot/_internal/renewal.py
  certbot/tests/renewal_test.py
Labels: area: renewal

#8350 Give DNS plugin snaps grade stable
  certbot-dns-cloudflare/snap/snapcraft.yaml
  certbot-dns-cloudxns/snap/snapcraft.yaml
  certbot-dns-digitalocean/snap/snapcraft.yaml
  certbot-dns-dnsimple/snap/snapcraft.yaml
  certbot-dns-dnsmadeeasy/snap/snapcraft.yaml
  certbot-dns-gehirn/snap/snapcraft.yaml
  certbot-dns-google/snap/snapcraft.yaml
  certbot-dns-linode/snap/snapcraft.yaml
  certbot-dns-luadns/snap/snapcraft.yaml
  certbot-dns-nsone/snap/snapcraft.yaml
  certbot-dns-ovh/snap/snapcraft.yaml
  certbot-dns-rfc2136/snap/snapcraft.yaml
  certbot-dns-route53/snap/snapcraft.yaml
  certbot-dns-sakuracloud/snap/snapcraft.yaml
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: dns, area: pkging, area: snaps

#8353 Add status messages to create_github_release script
  tools/create_github_release.py
Labels: area: pkging

#8341 certbot.util: suppress Popen CLI output
  certbot/certbot/util.py
Labels: area: ui / ux

#8351 Automate publishing snaps to the stable channel
  tools/create_github_release.py
  tools/finish_release.py
Labels: area: pkging, area: snaps, area: tooling

#8361 Move status message
  tools/finish_release.py
Labels: area: tooling, area: ui / ux

#8364 Remove PPA instructions from docs
  certbot/docs/install.rst
Labels: area: debian / ubuntu, area: documentation, area: pkging

#8268 Add query timeout for dns-rfc2136 plugin
  certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py
  certbot-dns-rfc2136/tests/dns_rfc2136_test.py
  certbot/CHANGELOG.md
Labels: area: dns

#8349 Add confirmation before certificate delete
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cert_manager.py
  certbot/tests/cert_manager_test.py
Labels: area: cert management, area: ui / ux

#8356 Add external snap docs and clean up dev docs
  certbot/docs/contributing.rst
  tools/snap/README.md
Labels: area: documentation, area: snaps, priority: significant

#8354 Deprecate certbot-auto on Debian systems
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  certbot/CHANGELOG.md
  letsencrypt-auto-source/Dockerfile.xenial
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh
  tox.ini
Labels: area: certbot-auto, area: pkging, area: testing, priority: high

#8381 manual: deprecate --manual-public-ip-logging-ok
  certbot-ci/certbot_integration_tests/utils/certbot_call.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/_internal/cli/report_config_interaction.py
  certbot/certbot/_internal/plugins/manual.py
  certbot/certbot/plugins/common.py
  certbot/tests/cli_test.py
  certbot/tests/plugins/manual_test.py
Labels: area: manual authenticator, area: ui / ux

#8382 Add .envrc for use with direnv
  .envrc
Labels: area: python, area: tooling

#8393 register: remove report_new_account, use logger, reword ToS prompt
  certbot/certbot/_internal/account.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/main.py
  certbot/tests/account_test.py
  certbot/tests/client_test.py
  certbot/tests/main_test.py
Labels: area: ui / ux

#8396 Execute basic integration tests against Certbot dockers during CI
  .azure-pipelines/templates/jobs/packaging-jobs.yml
Labels: area: docker, area: testing

#8408 Remove usage of buildkit
  tools/docker/build.sh
Labels: area: docker, area: pkging

#8404 Simplify/document snap creation
  certbot/docs/contributing.rst
  tools/snap/README.md
  tools/snap/generate_dnsplugins_all.sh
  tools/snap/generate_dnsplugins_postrefreshhook.sh
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: documentation, area: snaps, area: tooling

#8392 run: dont report new certs when only re-installing
  certbot/certbot/_internal/main.py
  certbot/tests/main_test.py
Labels: area: ui / ux

#8413 Fix Windows installer tests
  .azure-pipelines/templates/jobs/packaging-jobs.yml
Labels: area: python, area: testing, area: windows

#8414 Add Ubuntu 20.10 test farm tests
  certbot-apache/tests/apache-conf-files/apache-conf-test
  tests/letstest/apache2_targets.yaml
  tests/letstest/targets.yaml
Labels: area: apache, area: debian / ubuntu, area: testing

#8416 Fix LXD setup in snap README
  tools/snap/README.md
Labels: area: documentation, area: snaps

#8415 Remove fedora test farm tests
  tests/letstest/apache2_targets.yaml
  tests/letstest/auto_targets.yaml
  tests/letstest/targets.yaml
Labels: area: fedora / redhat / CentOS, area: testing

#8412 Update tools/snap/generate_* comments.
  certbot-dns-cloudflare/snap/hooks/post-refresh
  certbot-dns-cloudflare/snap/snapcraft.yaml
  certbot-dns-cloudxns/snap/hooks/post-refresh
  certbot-dns-cloudxns/snap/snapcraft.yaml
  certbot-dns-digitalocean/snap/hooks/post-refresh
  certbot-dns-digitalocean/snap/snapcraft.yaml
  certbot-dns-dnsimple/snap/hooks/post-refresh
  certbot-dns-dnsimple/snap/snapcraft.yaml
  certbot-dns-dnsmadeeasy/snap/hooks/post-refresh
  certbot-dns-dnsmadeeasy/snap/snapcraft.yaml
  certbot-dns-gehirn/snap/hooks/post-refresh
  certbot-dns-gehirn/snap/snapcraft.yaml
  certbot-dns-google/snap/hooks/post-refresh
  certbot-dns-google/snap/snapcraft.yaml
  certbot-dns-linode/snap/hooks/post-refresh
  certbot-dns-linode/snap/snapcraft.yaml
  certbot-dns-luadns/snap/hooks/post-refresh
  certbot-dns-luadns/snap/snapcraft.yaml
  certbot-dns-nsone/snap/hooks/post-refresh
  certbot-dns-nsone/snap/snapcraft.yaml
  certbot-dns-ovh/snap/hooks/post-refresh
  certbot-dns-ovh/snap/snapcraft.yaml
  certbot-dns-rfc2136/snap/hooks/post-refresh
  certbot-dns-rfc2136/snap/snapcraft.yaml
  certbot-dns-route53/snap/hooks/post-refresh
  certbot-dns-route53/snap/snapcraft.yaml
  certbot-dns-sakuracloud/snap/hooks/post-refresh
  certbot-dns-sakuracloud/snap/snapcraft.yaml
  tools/snap/generate_dnsplugins_postrefreshhook.sh
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: code health, area: documentation, area: snaps

#8410 Document that logs aren't always created
  tools/snap/README.md
Labels: area: documentation, area: snaps

#8411 Generate plugin snap configs as needed
  .gitignore
  certbot-dns-cloudflare/snap/hooks/post-refresh
  certbot-dns-cloudflare/snap/snapcraft.yaml
  certbot-dns-cloudxns/snap/hooks/post-refresh
  certbot-dns-cloudxns/snap/snapcraft.yaml
  certbot-dns-digitalocean/snap/hooks/post-refresh
  certbot-dns-digitalocean/snap/snapcraft.yaml
  certbot-dns-dnsimple/snap/hooks/post-refresh
  certbot-dns-dnsimple/snap/snapcraft.yaml
  certbot-dns-dnsmadeeasy/snap/hooks/post-refresh
  certbot-dns-dnsmadeeasy/snap/snapcraft.yaml
  certbot-dns-gehirn/snap/hooks/post-refresh
  certbot-dns-gehirn/snap/snapcraft.yaml
  certbot-dns-google/snap/hooks/post-refresh
  certbot-dns-google/snap/snapcraft.yaml
  certbot-dns-linode/snap/hooks/post-refresh
  certbot-dns-linode/snap/snapcraft.yaml
  certbot-dns-luadns/snap/hooks/post-refresh
  certbot-dns-luadns/snap/snapcraft.yaml
  certbot-dns-nsone/snap/hooks/post-refresh
  certbot-dns-nsone/snap/snapcraft.yaml
  certbot-dns-ovh/snap/hooks/post-refresh
  certbot-dns-ovh/snap/snapcraft.yaml
  certbot-dns-rfc2136/snap/hooks/post-refresh
  certbot-dns-rfc2136/snap/snapcraft.yaml
  certbot-dns-route53/snap/hooks/post-refresh
  certbot-dns-route53/snap/snapcraft.yaml
  certbot-dns-sakuracloud/snap/hooks/post-refresh
  certbot-dns-sakuracloud/snap/snapcraft.yaml
  tools/snap/build_remote.py
Labels: area: code health, area: dns, area: snaps, area: tooling
