Repository certbot/certbot, pull requests merged in 2020-08, with the labels that each got.

#8187 Document how to revoke snapcraft credentials
  .azure-pipelines/templates/stages/deploy-stage.yml
Labels: area: documentation, area: snaps

#8184 [Docs] Remove obsolete Gentoo installation instructions and add packages.
  certbot/docs/install.rst
Labels: area: documentation

#8189 Improve github release creation process
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/stages/changelog-stage.yml
  certbot/setup.py
  tools/create_github_release.py
  tools/dev_constraints.txt
  windows-installer/construct.py
Labels: area: code health, area: pkging, area: tooling

#8192 Add certbot-docker files to this repository preserving history
  tools/docker/LICENSE.txt
  tools/docker/README.md
  tools/docker/build.sh
  tools/docker/core/.gitignore
  tools/docker/core/Dockerfile
  tools/docker/core/README.md
  tools/docker/core/hooks/build
  tools/docker/core/hooks/post_push
  tools/docker/core/hooks/pre_build
  tools/docker/core/hooks/push
  tools/docker/deploy.sh
  tools/docker/lib/common
  tools/docker/plugin/.gitignore
  tools/docker/plugin/Dockerfile
  tools/docker/plugin/README.md
  tools/docker/plugin/hooks/build
  tools/docker/plugin/hooks/post_push
  tools/docker/plugin/hooks/pre_build
  tools/docker/plugin/hooks/push
Labels: area: docker, area: pkging, area: testing, area: tooling

#8194 Remove final jessie references outside of certbot-auto
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  letsencrypt-auto-source/Dockerfile.jessie
  letsencrypt-auto-source/rebuild_dependencies.py
  tox.ini
Labels: area: code health, area: testing

#8196 Remove release branch notification cruft
  .azure-pipelines/advanced-test.yml
Labels: area: code health, area: testing

#8195 Fix --archs default
  tools/snap/build_remote.py
Labels: area: code health, area: snaps, area: tooling

#8193 Automate Docker builds in Azure
  .azure-pipelines/release.yml
  .azure-pipelines/templates/stages/deploy-stage.yml
  tools/docker/LICENSE.txt
  tools/docker/README.md
  tools/docker/build.sh
  tools/docker/core/.gitignore
  tools/docker/core/Dockerfile
  tools/docker/core/README.md
  tools/docker/core/hooks/build
  tools/docker/core/hooks/post_push
  tools/docker/core/hooks/push
  tools/docker/deploy.sh
  tools/docker/lib/common
  tools/docker/plugin/.gitignore
  tools/docker/plugin/Dockerfile
  tools/docker/plugin/README.md
  tools/docker/plugin/hooks/build
  tools/docker/plugin/hooks/post_push
  tools/docker/plugin/hooks/push
Labels: area: docker, area: pkging, area: testing, area: tooling

#8200 You don't need to set --server
  certbot/docs/install.rst
Labels: area: docker, area: documentation

#8209 Fix certbot.compat.os docs
  certbot/certbot/compat/os.py
Labels: area: code health, area: documentation

#8206 Drop Python 3.5 support
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  acme/acme/__init__.py
  acme/setup.py
  certbot-apache/setup.py
  certbot-ci/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/certbot/_internal/main.py
  certbot/certbot/compat/filesystem.py
  certbot/docs/contributing.rst
  certbot/docs/install.rst
  certbot/setup.py
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tools/_venv_common.py
Labels: area: certbot-auto, area: code health, area: pkging, area: python, priority: high

#8217 Pin non-certbot-auto dependencies in our plugin snaps
  tools/snap/build_remote.py
Labels: area: pkging, area: snaps

#8214 Clean up our Docker scripts
  tools/docker/build.sh
  tools/docker/core/hooks/build
  tools/docker/core/hooks/post_push
  tools/docker/core/hooks/pre_build
  tools/docker/core/hooks/push
  tools/docker/deploy.sh
  tools/docker/lib/common
  tools/docker/plugin/hooks/build
  tools/docker/plugin/hooks/post_push
  tools/docker/plugin/hooks/pre_build
  tools/docker/plugin/hooks/push
Labels: area: code health, area: docker, area: tooling

#8218 Docker build improvements
  .azure-pipelines/advanced-test.yml
  .azure-pipelines/nightly.yml
  .azure-pipelines/release.yml
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/stages/deploy-stage.yml
  tools/docker/README.md
  tools/docker/build.sh
  tools/docker/deploy.sh
  tools/docker/lib/common
Labels: area: docker

#8222 Don't recommend using certbot-auto in Certbot's docs
  certbot/docs/contributing.rst
  certbot/docs/install.rst
Labels: area: certbot-auto, area: documentation

#8168 Update docs link in certbot unsupported error
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
Labels: area: certbot-auto, area: error handling

#8230 Fix finding Augeas in the ARM snaps
  certbot.wrapper
  certbot/CHANGELOG.md
  snap/snapcraft.yaml
Labels: area: apache, area: snaps, priority: high

#8234 Switch to the Debian Buster ARM image
  tests/letstest/apache2_targets.yaml
  tests/letstest/scripts/test_apache2.sh
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#8223 Clean up --register-unsafely-without-email docs
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/display/ops.py
Labels: area: code health, area: documentation
