Repository certbot/certbot, pull requests merged in 2020-09, with the labels that each got.

#8249 snap: Fix "stack smashing" error in wrapper
  certbot.wrapper
  certbot/CHANGELOG.md
  snap/hooks/configure
  snap/hooks/prepare-plug-plugin
  snap/snapcraft.yaml
Labels: area: snaps, priority: high

#8269 Release 1.8.0
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#8270 Add TODO to certbot.wrapper
  certbot.wrapper
Labels: area: code health, area: documentation, area: python, area: snaps

#8248 Move compatibility tests off of certbot-auto and Python 2
  certbot-compatibility-test/Dockerfile
  certbot-compatibility-test/certbot_compatibility_test/test_driver.py
  certbot-compatibility-test/certbot_compatibility_test/testdata/empty_cert.pem
  certbot-compatibility-test/certbot_compatibility_test/testdata/nginx.tar.gz
Labels: area: certbot-auto, area: code health, area: compatibility-test, area: python

#8279 Fix Certbot acme dependency
  certbot/CHANGELOG.md
  certbot/local-oldest-requirements.txt
  certbot/setup.py
Labels: area: pkging, priority: critical

#8244 Removed unneeded chmod-call in a test.
  certbot/tests/client_test.py
Labels: area: code health, area: testing

#8262 Remove deprecated `python setup.py test` call and update packager guide
  acme/setup.py
  certbot-apache/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/docs/packaging.rst
  certbot/setup.py
  tests/letstest/scripts/test_sdists.sh
Labels: area: documentation, area: pkging, area: testing

#8278 Delete conflicting server_names for random28524
  certbot-compatibility-test/nginx/nginx-roundtrip-testdata/79-configs/site-10571
  certbot-compatibility-test/nginx/nginx-roundtrip-testdata/79-configs/site-19791
Labels: area: code health, area: nginx

#8274 cli: add --preconfigured-renewal packaging flag
  certbot.wrapper
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/_internal/constants.py
  certbot/docs/packaging.rst
Labels: area: renewal, area: ui / ux, priority: high

#8237 nginx: reduced CLI logging when reloading nginx
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot-nginx/tests/configurator_test.py
  certbot/CHANGELOG.md
Labels: area: error handling, area: nginx, area: ui / ux

#8264 Removed unnecessary unittest.TestCase.setUp/tearDown calls.
  certbot-apache/tests/util.py
  certbot-dns-route53/tests/dns_route53_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/display/util_test.py
Labels: area: code health, area: testing

#8312 tests: remove Ubuntu 19.10
  tests/letstest/apache2_targets.yaml
  tests/letstest/auto_targets.yaml
  tests/letstest/targets.yaml
Labels: area: code health, area: testing

#8310 suppress tracebacks in ErrorHandler recovery
  certbot/CHANGELOG.md
  certbot/certbot/_internal/error_handler.py
Labels: area: error handling, area: ui / ux

#8316 Invoke pipstrap in tox and during the CI
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  .azure-pipelines/templates/steps/tox-steps.yml
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/pieces/pipstrap.py
  tox.ini
Labels: area: testing

#8321 Print more output from snapcraft remote-build
  tools/snap/build_remote.py
Labels: area: error handling, area: snaps, area: tooling

#8319 Disable build isolation during snap dns plugins build
  certbot-dns-cloudflare/snap/snapcraft.yaml
  certbot-dns-cloudxns/snap/snapcraft.yaml
  certbot-dns-digitalocean/snap/snapcraft.yaml
  certbot-dns-dnsimple/snap/snapcraft.yaml
  certbot-dns-dnsmadeeasy/snap/snapcraft.yaml
  certbot-dns-gehirn/snap/snapcraft.yaml
  certbot-dns-google/snap/snapcraft.yaml
  certbot-dns-linode/snap/snapcraft.yaml
  certbot-dns-luadns/snap/snapcraft.yaml
  certbot-dns-nsone/snap/snapcraft.yaml
  certbot-dns-ovh/snap/snapcraft.yaml
  certbot-dns-rfc2136/snap/snapcraft.yaml
  certbot-dns-route53/snap/snapcraft.yaml
  certbot-dns-sakuracloud/snap/snapcraft.yaml
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: snaps

#8300 Retry Snap upload in pipeline
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/stages/changelog-stage.yml
  .azure-pipelines/templates/stages/deploy-stage.yml
  .azure-pipelines/templates/stages/notify-failure-stage.yml
  .azure-pipelines/templates/steps/tox-steps.yml
Labels: area: snaps, area: tooling

#8323 Revert "Disable build isolation during snap dns plugins build (#8319)"
  certbot-dns-cloudflare/snap/snapcraft.yaml
  certbot-dns-cloudxns/snap/snapcraft.yaml
  certbot-dns-digitalocean/snap/snapcraft.yaml
  certbot-dns-dnsimple/snap/snapcraft.yaml
  certbot-dns-dnsmadeeasy/snap/snapcraft.yaml
  certbot-dns-gehirn/snap/snapcraft.yaml
  certbot-dns-google/snap/snapcraft.yaml
  certbot-dns-linode/snap/snapcraft.yaml
  certbot-dns-luadns/snap/snapcraft.yaml
  certbot-dns-nsone/snap/snapcraft.yaml
  certbot-dns-ovh/snap/snapcraft.yaml
  certbot-dns-rfc2136/snap/snapcraft.yaml
  certbot-dns-route53/snap/snapcraft.yaml
  certbot-dns-sakuracloud/snap/snapcraft.yaml
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: pkging, area: snaps, area: tooling

#8313 Refactor certbot snap wrapper
  certbot.wrapper
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/snap_config.py
  snap/snapcraft.yaml
Labels: area: snaps
