Repository certbot/certbot, pull requests merged in 2020-12, with the labels that each got.

#8487 Update files from 1.10.0 release
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: documentation, area: pkging, priority: significant

#8488 Fix changelog typo
  certbot/CHANGELOG.md
Labels: area: code health, area: documentation, priority: significant

#8498 Remove CentOS 6 tests
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  letsencrypt-auto-source/Dockerfile.redhat6
  letsencrypt-auto-source/tests/__init__.py
  letsencrypt-auto-source/tests/auto_test.py
  letsencrypt-auto-source/tests/centos6_tests.sh
  letsencrypt-auto-source/tests/certs/ca/my-root-ca.crt.pem
  letsencrypt-auto-source/tests/certs/ca/my-root-ca.key.pem
  letsencrypt-auto-source/tests/certs/ca/my-root-ca.srl
  letsencrypt-auto-source/tests/certs/localhost/cert.pem
  letsencrypt-auto-source/tests/certs/localhost/localhost.csr.pem
  letsencrypt-auto-source/tests/certs/localhost/privkey.pem
  letsencrypt-auto-source/tests/certs/localhost/server.pem
  letsencrypt-auto-source/tests/fake-letsencrypt/dist/letsencrypt-99.9.9.tar.gz
  letsencrypt-auto-source/tests/fake-letsencrypt/letsencrypt.py
  letsencrypt-auto-source/tests/fake-letsencrypt/setup.py
  letsencrypt-auto-source/tests/oraclelinux6_tests.sh
  letsencrypt-auto-source/tests/uname_wrapper.sh
  tests/letstest/auto_targets.yaml
  tests/letstest/targets.yaml
  tox.ini
Labels: area: fedora / redhat / CentOS, area: testing, priority: high

#8499 Remove centos6 tests 1.10.x
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  letsencrypt-auto-source/Dockerfile.redhat6
  letsencrypt-auto-source/tests/__init__.py
  letsencrypt-auto-source/tests/auto_test.py
  letsencrypt-auto-source/tests/centos6_tests.sh
  letsencrypt-auto-source/tests/certs/ca/my-root-ca.crt.pem
  letsencrypt-auto-source/tests/certs/ca/my-root-ca.key.pem
  letsencrypt-auto-source/tests/certs/ca/my-root-ca.srl
  letsencrypt-auto-source/tests/certs/localhost/cert.pem
  letsencrypt-auto-source/tests/certs/localhost/localhost.csr.pem
  letsencrypt-auto-source/tests/certs/localhost/privkey.pem
  letsencrypt-auto-source/tests/certs/localhost/server.pem
  letsencrypt-auto-source/tests/fake-letsencrypt/dist/letsencrypt-99.9.9.tar.gz
  letsencrypt-auto-source/tests/fake-letsencrypt/letsencrypt.py
  letsencrypt-auto-source/tests/fake-letsencrypt/setup.py
  letsencrypt-auto-source/tests/oraclelinux6_tests.sh
  letsencrypt-auto-source/tests/uname_wrapper.sh
  tests/letstest/auto_targets.yaml
  tests/letstest/targets.yaml
  tox.ini
Labels: area: fedora / redhat / CentOS, area: pkging, area: testing

#8500 Fix add deprecated argument
  certbot-ci/certbot_integration_tests/utils/certbot_call.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli/helpful.py
  certbot/certbot/util.py
  certbot/tests/helpful_test.py
Labels: area: code health, area: ui / ux, bug, priority: high

#8501 Fix add deprecated argument on 1.10.x
  certbot-ci/certbot_integration_tests/utils/certbot_call.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli/helpful.py
  certbot/certbot/util.py
  certbot/tests/helpful_test.py
Labels: area: pkging, area: ui / ux, bug

#8505 Candidate 1.10.1
  certbot-auto
  certbot/CHANGELOG.md
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: pkging

#8506 Candidate 1.10.1 1.10.x
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: pkging

#8503 cli: clean up `certbot renew` summary
  certbot/certbot/_internal/renewal.py
  certbot/tests/renewal_test.py
Labels: area: renewal, area: ui / ux

#8467 Update both main VA and remote VA to use the provided DNS server
  certbot-ci/certbot_integration_tests/utils/acme_server.py
Labels: area: dns, area: testing

#8482 dns-google: improve credentials error message
  certbot-dns-google/certbot_dns_google/_internal/dns_google.py
  certbot-dns-google/tests/dns_google_test.py
Labels: area: dns, area: error handling

#8424 Removed some unused imports.
  acme/acme/__init__.py
  certbot-ci/windows_installer_integration_tests/conftest.py
  certbot/certbot/_internal/plugins/null.py
  certbot/tests/client_test.py
  certbot/tests/compat/filesystem_test.py
Labels: area: code health

#8469 add coverage testing to dns-rfc2136 integration
  tox.ini
Labels: area: dns, area: testing

#8489 Completely deprecate certbot-auto
  certbot/CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tests/letstest/scripts/test_leauto_upgrades.sh
  tests/letstest/scripts/test_letsencrypt_auto_certonly_standalone.sh
Labels: area: certbot-auto, area: code health, area: testing, priority: high

#8491 Deprecate support for Python 2
  acme/acme/__init__.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/certbot/_internal/main.py
  pytest.ini
Labels: area: code health, priority: high

#8445 Remove the --system-site-package from snap build
  snap/snapcraft.yaml
Labels: area: code health, area: snaps, priority: significant

#8516 Deprecate support of Apache 2.2 in certbot-apache
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot/CHANGELOG.md
Labels: area: apache, area: code health, priority: significant

#8522 Add finish_release.py CLI parsing and flags
  tools/finish_release.py
Labels: area: pkging, area: tooling

#8484 Setup a timeout to the remote snap build process
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  tools/snap/build_remote.py
Labels: area: code health, area: snaps, area: testing, priority: significant

#8538 Add path to certbot executable in debug log
  certbot/certbot/_internal/main.py
Labels: area: logging

#8443 Enable again build isolation with proper pinning of build dependencies
  snap/snapcraft.yaml
  tools/docker/core/Dockerfile
  tools/docker/plugin/Dockerfile
  tools/pip_install.py
  tools/pipstrap.py
  tools/pipstrap_constraints.txt
  windows-installer/construct.py
Labels: area: code health, area: pkging, area: tooling, priority: high

#8450 Added certbot-ci to lint section. Silenced and fixed linting warnings.
  acme/acme/crypto_util.py
  certbot-ci/certbot_integration_tests/certbot_tests/__init__.py
  certbot-ci/certbot_integration_tests/certbot_tests/context.py
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot-ci/certbot_integration_tests/conftest.py
  certbot-ci/certbot_integration_tests/nginx_tests/context.py
  certbot-ci/certbot_integration_tests/nginx_tests/test_main.py
  certbot-ci/certbot_integration_tests/rfc2136_tests/context.py
  certbot-ci/certbot_integration_tests/rfc2136_tests/test_main.py
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-ci/certbot_integration_tests/utils/certbot_call.py
  certbot-ci/certbot_integration_tests/utils/constants.py
  certbot-ci/certbot_integration_tests/utils/dns_server.py
  certbot-ci/certbot_integration_tests/utils/misc.py
  certbot-ci/certbot_integration_tests/utils/pebble_artifacts.py
  certbot-ci/certbot_integration_tests/utils/pebble_ocsp_server.py
  certbot-ci/certbot_integration_tests/utils/proxy.py
  linter_plugin.py
  tox.ini
Labels: area: code health, area: testing

#8531 Remove reference to letsencrypt(-auto)
  certbot/README.rst
Labels: area: certbot-auto, area: documentation

#8532 Clean up certbot-auto docs
  certbot/CHANGELOG.md
  certbot/docs/compatibility.rst
  certbot/docs/install.rst
  certbot/docs/using.rst
Labels: area: certbot-auto, area: documentation

#8521 Fix fetch of existing records from Google DNS
  AUTHORS.md
  certbot-dns-google/certbot_dns_google/_internal/dns_google.py
  certbot-dns-google/tests/dns_google_test.py
  certbot/CHANGELOG.md
Labels: area: dns

#8553 Pin DNS plugin snap build dependencies
  tools/snap/generate_dnsplugins_all.sh
  tools/snap/generate_dnsplugins_snapcraft.sh
Labels: area: code health, area: pkging, area: snaps

#8479 Flag that DNS plugins are distributed separately from Certbot
  certbot-dns-cloudflare/certbot_dns_cloudflare/__init__.py
  certbot-dns-cloudxns/certbot_dns_cloudxns/__init__.py
  certbot-dns-digitalocean/certbot_dns_digitalocean/__init__.py
  certbot-dns-dnsimple/certbot_dns_dnsimple/__init__.py
  certbot-dns-dnsmadeeasy/certbot_dns_dnsmadeeasy/__init__.py
  certbot-dns-gehirn/certbot_dns_gehirn/__init__.py
  certbot-dns-google/certbot_dns_google/__init__.py
  certbot-dns-linode/certbot_dns_linode/__init__.py
  certbot-dns-luadns/certbot_dns_luadns/__init__.py
  certbot-dns-nsone/certbot_dns_nsone/__init__.py
  certbot-dns-ovh/certbot_dns_ovh/__init__.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/__init__.py
  certbot-dns-route53/certbot_dns_route53/__init__.py
  certbot-dns-sakuracloud/certbot_dns_sakuracloud/__init__.py
Labels: area: dns, area: documentation

#8549 Fix TTL mismatch leading to HTTP 412
  certbot-dns-google/certbot_dns_google/_internal/dns_google.py
  certbot-dns-google/tests/dns_google_test.py
  certbot/CHANGELOG.md
Labels: area: dns, priority: significant

#8552 Add certbot-auto uninstall docs
  certbot/docs/install.rst
  certbot/docs/uninstall.rst
Labels: area: certbot-auto, area: documentation

#8541 Edit certs -> certificates in user-facing text.
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot-dns-digitalocean/certbot_dns_digitalocean/_internal/dns_digitalocean.py
  certbot-dns-linode/certbot_dns_linode/_internal/dns_linode.py
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot/README.rst
  certbot/certbot/_internal/cert_manager.py
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/_internal/storage.py
  certbot/certbot/crypto_util.py
  certbot/certbot/ocsp.py
  certbot/docs/contributing.rst
  certbot/docs/install.rst
  certbot/docs/using.rst
  certbot/tests/main_test.py
  certbot/tests/renewal_test.py
Labels: area: ui / ux
