Repository certbot/certbot, pull requests merged in 2021-01, with the labels that each got.

#8472 Forbid os.readlink()
  certbot/certbot/_internal/account.py
  certbot/certbot/_internal/storage.py
  certbot/certbot/compat/filesystem.py
  certbot/certbot/compat/os.py
  certbot/tests/cert_manager_test.py
  certbot/tests/compat/filesystem_test.py
  certbot/tests/storage_test.py
Labels: area: cert management, area: code health, area: windows, priority: significant

#8573 Update files from 1.11.0 release
  acme/setup.py
  certbot-apache/setup.py
  certbot-auto
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
  letsencrypt-auto
  letsencrypt-auto-source/certbot-auto.asc
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.sig
  letsencrypt-auto-source/pieces/certbot-requirements.txt
Labels: area: certbot-auto, area: pkging

#8575 Skip meta creation to speed up tests
  certbot/tests/account_test.py
Labels: area: macOS, area: testing

#8465 Enable Python 3.8 for Certbot on Windows
  .azure-pipelines/templates/jobs/packaging-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  certbot/setup.py
  tools/dev_constraints.txt
  windows-installer/construct.py
  windows-installer/template.nsi
Labels: area: pkging, area: testing, area: windows, priority: significant

#8574 Modify release script to support signing certbot-auto with a yubikey
  tools/_release.sh
Labels: area: pkging, area: ui / ux

#8600 Always sign certbot-auto with a yubikey
  tools/_release.sh
  tools/offline-sigrequest.sh
Labels: area: certbot-auto, area: code health, area: pkging

#8605 Minor fix to logging message
  acme/acme/crypto_util.py
Labels: area: acme, area: logging

#8607 Remove unused PyICU pinning
  tools/oldest_constraints.txt
Labels: area: code health, area: testing

#8591 Drop Python 2 support
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  acme/acme/__init__.py
  acme/setup.py
  certbot-apache/setup.py
  certbot-ci/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/certbot/_internal/main.py
  certbot/docs/contributing.rst
  certbot/docs/install.rst
  certbot/setup.py
  pytest.ini
  tools/dev_constraints.txt
Labels: area: code health, area: python, priority: high
