Repository certbot/certbot, pull requests merged in 2021-03, with the labels that each got.

#8694 Removed a Python 2 fallback in certbot.Reverter.
  certbot-apache/certbot_apache/_internal/parser.py
  certbot/certbot/reverter.py
Labels: area: code health, area: python

#8706 Final update to certbot-auto
  certbot/CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tests/letstest/scripts/test_leauto_upgrades.sh
Labels: area: certbot-auto, area: pkging, priority: high

#8442 Kill current snapcraft build when a "Chroot problem" is encountered
  tools/snap/build_remote.py
Labels: area: snaps, area: tooling, priority: significant

#8720 Fix linux-py39-cover test
  tools/dev_constraints.txt
  tools/pipstrap_constraints.txt
Labels: area: testing, bug
