Repository certbot/certbot, pull requests merged in 2021-05, with the labels that each got.

#8841 Fix sphinx followup
  .azure-pipelines/templates/steps/sphinx-steps.yml
  tools/pinning/pyproject.toml
Labels: area: code health, area: documentation, area: testing

#8844 Add 3rd party certbot-dns-godaddy to the docs
  certbot/docs/using.rst
Labels: area: dns, area: documentation

#8789 Use UTF-8 for renewal configuration file encoding
  certbot/CHANGELOG.md
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/storage.py
Labels: priority: unplanned

#8836 [Windows] Cleanup Certbot pkg dir before installing to avoid dependencies conflicts
  certbot/CHANGELOG.md
  windows-installer/assets/template.nsi
Labels: area: windows

#8850 cli: dont double-print choosing plugins error
  certbot/certbot/_internal/main.py
Labels: area: error handling, area: ui / ux

#8852 Command-line UX overhaul
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/certbot_apache/_internal/display_ops.py
  certbot-apache/certbot_apache/_internal/override_debian.py
  certbot-apache/local-oldest-requirements.txt
  certbot-apache/setup.py
  certbot-apache/tests/autohsts_test.py
  certbot-apache/tests/centos6_test.py
  certbot-apache/tests/configurator_test.py
  certbot-compatibility-test/certbot_compatibility_test/test_driver.py
  certbot-dns-cloudflare/tests/dns_cloudflare_test.py
  certbot-dns-digitalocean/tests/dns_digitalocean_test.py
  certbot-dns-google/tests/dns_google_test.py
  certbot-dns-rfc2136/tests/dns_rfc2136_test.py
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot-nginx/certbot_nginx/_internal/http_01.py
  certbot-nginx/certbot_nginx/_internal/parser.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  certbot-nginx/tests/configurator_test.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/auth_handler.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/constants.py
  certbot/certbot/_internal/hooks.py
  certbot/certbot/_internal/log.py
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/plugins/manual.py
  certbot/certbot/_internal/plugins/selection.py
  certbot/certbot/_internal/plugins/webroot.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/_internal/storage.py
  certbot/certbot/_internal/updater.py
  certbot/certbot/compat/misc.py
  certbot/certbot/crypto_util.py
  certbot/certbot/display/ops.py
  certbot/certbot/ocsp.py
  certbot/certbot/plugins/common.py
  certbot/certbot/plugins/dns_common.py
  certbot/certbot/plugins/dns_test_common_lexicon.py
  certbot/certbot/reverter.py
  certbot/certbot/util.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/client_test.py
  certbot/tests/compat/misc_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/hook_test.py
  certbot/tests/log_test.py
  certbot/tests/main_test.py
  certbot/tests/plugins/common_test.py
  certbot/tests/plugins/dns_common_test.py
  certbot/tests/plugins/manual_test.py
  certbot/tests/util_test.py
  tests/lock_test.py
Labels: area: ui / ux

#8866 Remove no names found in configuration files because it sounds like an error but actually it is fine
  certbot/certbot/display/ops.py
  certbot/tests/display/ops_test.py
Labels: area: acme

#8860 cli: later printing of renewal and install retry advice
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/main.py
  certbot/tests/client_test.py
  certbot/tests/main_test.py
Labels: area: ui / ux, priority: high

#8862 Remove unused tools
  tools/deactivate.py
  tools/half-sign.c
  tools/simple_http_server.py
Labels: area: code health

#8870 Add instructions for setting up a cronjob in the docs
  certbot/docs/using.rst
Labels: area: documentation, area: renewal, area: ui / ux

#8869 Deprecate usage of IConfig as a singleton in Certbot
  certbot-compatibility-test/certbot_compatibility_test/configurators/nginx/common.py
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot-nginx/local-oldest-requirements.txt
  certbot-nginx/setup.py
  certbot-nginx/tests/test_util.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/auth_handler.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/crypto_util.py
  certbot/tests/auth_handler_test.py
  certbot/tests/client_test.py
  certbot/tests/crypto_util_test.py
Labels: area: code health

#8874 Use shortlink for renewal setup instructions
  certbot/certbot/_internal/main.py
Labels: area: documentation, area: renewal, area: ui / ux, priority: high
