Repository certbot/certbot, pull requests merged in 2021-11, with the labels that each got.

#9089 fix a typo in gen_ss_cert type hint
  acme/acme/crypto_util.py
Labels: area: acme, area: mypy

#9077 Add Python 3.10 support and tests
  .azure-pipelines/templates/jobs/extended-tests-jobs.yml
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  acme/setup.py
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/certbot_apache/_internal/entrypoint.py
  certbot-apache/setup.py
  certbot-ci/certbot_integration_tests/utils/certbot_call.py
  certbot-ci/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/storage.py
  certbot/certbot/util.py
  certbot/setup.py
  certbot/tests/util_test.py
  letstest/scripts/test_openssl_version.py
  letstest/setup.py
  pytest.ini
  tools/venv.py
  windows-installer/setup.py
Labels: area: testing, area: python

#9085 Add type annotations to the certbot package (part 2)
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/certbot_apache/_internal/http_01.py
  certbot-dns-linode/certbot_dns_linode/_internal/dns_linode.py
  certbot-nginx/certbot_nginx/_internal/configurator.py
  certbot-nginx/certbot_nginx/_internal/http_01.py
  certbot/certbot/compat/filesystem.py
  certbot/certbot/compat/misc.py
  certbot/certbot/display/ops.py
  certbot/certbot/display/util.py
  certbot/certbot/plugins/common.py
  certbot/certbot/plugins/dns_common.py
  certbot/certbot/plugins/dns_common_lexicon.py
  certbot/certbot/plugins/dns_test_common.py
  certbot/certbot/plugins/dns_test_common_lexicon.py
  certbot/certbot/plugins/enhancements.py
  certbot/certbot/plugins/storage.py
  certbot/certbot/plugins/util.py
  certbot/certbot/util.py
  certbot/tests/display/ops_test.py
Labels: area: python, area: mypy, priority: significant

#9086 Add type annotations to the certbot package (part 3)
  certbot/certbot/_internal/account.py
  certbot/certbot/_internal/auth_handler.py
  certbot/certbot/_internal/cert_manager.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/constants.py
  certbot/certbot/_internal/eff.py
  certbot/certbot/_internal/error_handler.py
  certbot/certbot/_internal/hooks.py
  certbot/certbot/_internal/lock.py
  certbot/certbot/_internal/log.py
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/_internal/reporter.py
  certbot/certbot/_internal/snap_config.py
  certbot/certbot/_internal/storage.py
  certbot/certbot/_internal/updater.py
Labels: area: python, area: mypy

#9087 Add type annotations to the certbot package (part 4)
  acme/acme/messages.py
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/_internal/cli/cli_utils.py
  certbot/certbot/_internal/cli/group_adder.py
  certbot/certbot/_internal/cli/helpful.py
  certbot/certbot/_internal/cli/paths_parser.py
  certbot/certbot/_internal/cli/plugins_parsing.py
  certbot/certbot/_internal/cli/subparsers.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/display/completer.py
  certbot/certbot/_internal/display/dummy_readline.py
  certbot/certbot/_internal/display/obj.py
  certbot/certbot/_internal/display/util.py
  certbot/certbot/_internal/plugins/disco.py
  certbot/certbot/_internal/plugins/manual.py
  certbot/certbot/_internal/plugins/null.py
  certbot/certbot/_internal/plugins/selection.py
  certbot/certbot/_internal/plugins/standalone.py
  certbot/certbot/_internal/plugins/webroot.py
  tox.ini
Labels: area: python, area: mypy

#9120 Fully type certbot-ci module
  certbot-ci/certbot_integration_tests/assets/hook.py
  certbot-ci/certbot_integration_tests/certbot_tests/assertions.py
  certbot-ci/certbot_integration_tests/certbot_tests/context.py
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot-ci/certbot_integration_tests/conftest.py
  certbot-ci/certbot_integration_tests/nginx_tests/context.py
  certbot-ci/certbot_integration_tests/nginx_tests/nginx_config.py
  certbot-ci/certbot_integration_tests/nginx_tests/test_main.py
  certbot-ci/certbot_integration_tests/py.typed
  certbot-ci/certbot_integration_tests/rfc2136_tests/context.py
  certbot-ci/certbot_integration_tests/rfc2136_tests/test_main.py
  certbot-ci/certbot_integration_tests/utils/acme_server.py
  certbot-ci/certbot_integration_tests/utils/certbot_call.py
  certbot-ci/certbot_integration_tests/utils/dns_server.py
  certbot-ci/certbot_integration_tests/utils/misc.py
  certbot-ci/certbot_integration_tests/utils/pebble_artifacts.py
  certbot-ci/certbot_integration_tests/utils/pebble_ocsp_server.py
  certbot-ci/certbot_integration_tests/utils/proxy.py
  certbot-ci/snap_integration_tests/conftest.py
  certbot-ci/snap_integration_tests/dns_tests/test_main.py
  certbot-ci/snap_integration_tests/py.typed
  certbot-ci/windows_installer_integration_tests/conftest.py
  certbot-ci/windows_installer_integration_tests/py.typed
  certbot-ci/windows_installer_integration_tests/test_main.py
  linter_plugin.py
  tox.ini
Labels: area: python, area: mypy
