Repository certbot/certbot, pull requests merged in 2021-08, with the labels that each got.

#8963 Make display classes implement IDisplay
  certbot/certbot/_internal/display/obj.py
Labels: area: code health, area: testing

#8955 snap: workaround for snapctl crash in plugin hook
  certbot/CHANGELOG.md
  snap/hooks/prepare-plug-plugin
Labels: area: debian / ubuntu, area: snaps

#8910 docs: add "Deleting Certificates" to user guide
  certbot/docs/using.rst
Labels: area: cert management, area: documentation

#8979 docs: add basic intro to certbot in user guide
  certbot/docs/using.rst
Labels: area: documentation

#8987 Cleanup some useless type ignore directives
  acme/acme/challenges.py
  acme/acme/crypto_util.py
  acme/acme/magic_typing.py
  acme/acme/messages.py
  certbot-compatibility-test/certbot_compatibility_test/interfaces.py
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/_internal/client.py
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/plugins/disco.py
  certbot/certbot/compat/filesystem.py
  certbot/certbot/crypto_util.py
  certbot/certbot/ocsp.py
  certbot/docs/contributing.rst
  certbot/tests/log_test.py
  certbot/tests/ocsp_test.py
  certbot/tests/reporter_test.py
  tests/lock_test.py
Labels: area: code health, area: mypy

#8990 certbot-dns-rfc2136: catch error when a hostname is being used for `dns_rfc2136_server`
  certbot-dns-rfc2136/certbot_dns_rfc2136/__init__.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py
  certbot-dns-rfc2136/tests/dns_rfc2136_test.py
  certbot/CHANGELOG.md
Labels: area: ui / ux, area: error handling, area: dns, priority: significant
