Repository certbot/certbot, pull requests merged in 2021-12, with the labels that each got.

#9126 Fully type lock_test.py
  tests/lock_test.py
  tox.ini
Labels: area: mypy

#9133 Fully type certbot-compatibility-test
  certbot-compatibility-test/certbot_compatibility_test/configurators/apache/common.py
  certbot-compatibility-test/certbot_compatibility_test/configurators/common.py
  certbot-compatibility-test/certbot_compatibility_test/configurators/nginx/common.py
  certbot-compatibility-test/certbot_compatibility_test/interfaces.py
  certbot-compatibility-test/certbot_compatibility_test/test_driver.py
  certbot-compatibility-test/certbot_compatibility_test/util.py
  certbot-compatibility-test/certbot_compatibility_test/validator.py
  certbot-compatibility-test/certbot_compatibility_test/validator_test.py
  tox.ini
Labels: area: mypy

#9125 Fully type all DNS plugins
  certbot-dns-cloudflare/certbot_dns_cloudflare/_internal/dns_cloudflare.py
  certbot-dns-cloudxns/certbot_dns_cloudxns/_internal/dns_cloudxns.py
  certbot-dns-digitalocean/certbot_dns_digitalocean/_internal/dns_digitalocean.py
  certbot-dns-dnsimple/certbot_dns_dnsimple/_internal/dns_dnsimple.py
  certbot-dns-dnsmadeeasy/certbot_dns_dnsmadeeasy/_internal/dns_dnsmadeeasy.py
  certbot-dns-gehirn/certbot_dns_gehirn/_internal/dns_gehirn.py
  certbot-dns-google/certbot_dns_google/_internal/dns_google.py
  certbot-dns-linode/certbot_dns_linode/_internal/dns_linode.py
  certbot-dns-luadns/certbot_dns_luadns/_internal/dns_luadns.py
  certbot-dns-nsone/certbot_dns_nsone/_internal/dns_nsone.py
  certbot-dns-ovh/certbot_dns_ovh/_internal/dns_ovh.py
  certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py
  certbot-dns-route53/certbot_dns_route53/_internal/dns_route53.py
  certbot-dns-route53/certbot_dns_route53/authenticator.py
  certbot-dns-sakuracloud/certbot_dns_sakuracloud/_internal/dns_sakuracloud.py
  certbot/certbot/plugins/dns_common_lexicon.py
  tox.ini
Labels: area: mypy

#9146 Document appending behaviour of `max-log-backups = 0` in User Guide
  certbot/docs/using.rst
Labels: area: documentation

#9127 Add `show_account` subcommand to retrieve account info from ACME server
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli/cli_constants.py
  certbot/certbot/_internal/cli/helpful.py
  certbot/certbot/_internal/cli/paths_parser.py
  certbot/certbot/_internal/cli/verb_help.py
  certbot/certbot/_internal/main.py
  certbot/tests/main_test.py
Labels: area: ui / ux, priority: significant
