Repository certbot/certbot, pull requests merged in 2021-04, with the labels that each got.

#8747 fix various fd leaks
  certbot/certbot/_internal/main.py
  certbot/tests/log_test.py
  certbot/tests/plugins/webroot_test.py
Labels: area: testing

#8770 Expand manual DNS challenge instructions to include mention of propagation time and tool to check this
  certbot/certbot/_internal/plugins/manual.py
Labels: area: dns, area: manual authenticator, area: ui / ux

#8799 Fix ciphers link
  certbot/docs/ciphers.rst
  certbot/docs/conf.py
Labels: area: documentation

#8797 Remove modifications to certbot-auto from the release script
  tools/_release.sh
  tools/eff-pubkey.pem
Labels: area: certbot-auto, area: tooling

#8805 Update certbot-auto modification checks
  .azure-pipelines/templates/jobs/standard-tests-jobs.yml
  letsencrypt-auto-source/letsencrypt-auto
  tests/modification-check.py
  tox.ini
Labels: area: certbot-auto, area: code health, area: testing

#8811 Don't ignore "kgs"
  .gitignore
Labels: area: code health, area: pkging, area: tooling

#8792 Update assertTrue/False to Python 3 precise asserts
  acme/tests/challenges_test.py
  acme/tests/client_test.py
  acme/tests/crypto_util_test.py
  acme/tests/errors_test.py
  acme/tests/jws_test.py
  acme/tests/messages_test.py
  certbot/tests/account_test.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/cli_test.py
  certbot/tests/client_test.py
  certbot/tests/compat/filesystem_test.py
  certbot/tests/compat/misc_test.py
  certbot/tests/crypto_util_test.py
  certbot/tests/display/completer_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/display/util_test.py
  certbot/tests/eff_test.py
  certbot/tests/error_handler_test.py
  certbot/tests/helpful_test.py
  certbot/tests/hook_test.py
  certbot/tests/lock_test.py
  certbot/tests/log_test.py
  certbot/tests/main_test.py
  certbot/tests/ocsp_test.py
  certbot/tests/plugins/common_test.py
  certbot/tests/plugins/disco_test.py
  certbot/tests/plugins/dns_common_test.py
  certbot/tests/plugins/manual_test.py
  certbot/tests/plugins/null_test.py
  certbot/tests/plugins/selection_test.py
  certbot/tests/plugins/standalone_test.py
  certbot/tests/plugins/storage_test.py
  certbot/tests/plugins/util_test.py
  certbot/tests/plugins/webroot_test.py
  certbot/tests/renewal_test.py
  certbot/tests/renewupdater_test.py
  certbot/tests/reporter_test.py
  certbot/tests/reverter_test.py
  certbot/tests/storage_test.py
  certbot/tests/util_test.py
Labels: area: code health, area: testing, priority: significant
