Repository certbot/certbot, pull requests merged in 2021-02, with the labels that each got.

#8623 Start disabling certbot-auto upgrades
  certbot/CHANGELOG.md
  letsencrypt-auto-source/letsencrypt-auto
  letsencrypt-auto-source/letsencrypt-auto.template
  tests/letstest/auto_targets.yaml
  tests/letstest/scripts/test_leauto_upgrades.sh
Labels: area: certbot-auto

#8638 Remove crufty pytest exception
  pytest.ini
Labels: area: code health, area: testing

#8639 Merge dev and dev3 extras
  certbot/setup.py
  tools/venv.py
  tox.ini
Labels: area: code health, area: python

#8603 Update cli.ini
  certbot/examples/cli.ini
Labels: area: documentation, priority: unplanned

#8674 Remove import fallback for collections.abc
  acme/acme/messages.py
  certbot/certbot/_internal/plugins/disco.py
Labels: area: code health

#8673 Removed backport of unittest.assertLogs
  certbot-nginx/tests/test_log_util.py
  certbot-nginx/tests/test_util.py
Labels: area: code health

#8685 Remove check for 'fake' in issuer name when renewing certs
  certbot/certbot/_internal/renewal.py
  certbot/tests/main_test.py
Labels: area: testing

#8645 Insert new line before "More details about these changes can be found on our GitHub repo."
  tools/extract_changelog.py
Labels: area: documentation, area: pkging
