Repository certbot/certbot, pull requests merged in 2021-07, with the labels that each got.

#8933 Update files from 1.17.0 release
  acme/setup.py
  certbot-apache/setup.py
  certbot-compatibility-test/setup.py
  certbot-dns-cloudflare/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-digitalocean/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-google/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-rfc2136/setup.py
  certbot-dns-route53/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot-nginx/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/__init__.py
  certbot/docs/cli-help.txt
Labels: area: documentation, area: pkging

#8931 acme: deprecate ACMEv1 client classes
  acme/acme/client.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/client.py
Labels: area: acme

#8835 Deprecate zope.component in favor of an direct calls to functions from `certbot.display.util` module
  certbot-apache/certbot_apache/_internal/configurator.py
  certbot-apache/certbot_apache/_internal/display_ops.py
  certbot-apache/tests/configurator_test.py
  certbot-apache/tests/debian_test.py
  certbot-apache/tests/display_ops_test.py
  certbot-apache/tests/util.py
  certbot-compatibility-test/certbot_compatibility_test/test_driver.py
  certbot-dns-cloudflare/tests/dns_cloudflare_test.py
  certbot-dns-digitalocean/tests/dns_digitalocean_test.py
  certbot-dns-google/tests/dns_google_test.py
  certbot-dns-rfc2136/tests/dns_rfc2136_test.py
  certbot-nginx/certbot_nginx/_internal/display_ops.py
  certbot-nginx/tests/display_ops_test.py
  certbot-nginx/tests/test_util.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/auth_handler.py
  certbot/certbot/_internal/cert_manager.py
  certbot/certbot/_internal/cli/helpful.py
  certbot/certbot/_internal/display/obj.py
  certbot/certbot/_internal/eff.py
  certbot/certbot/_internal/main.py
  certbot/certbot/_internal/plugins/disco.py
  certbot/certbot/_internal/plugins/manual.py
  certbot/certbot/_internal/plugins/selection.py
  certbot/certbot/_internal/plugins/standalone.py
  certbot/certbot/_internal/plugins/webroot.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/crypto_util.py
  certbot/certbot/display/ops.py
  certbot/certbot/display/util.py
  certbot/certbot/plugins/dns_test_common_lexicon.py
  certbot/certbot/tests/util.py
  certbot/tests/auth_handler_test.py
  certbot/tests/cert_manager_test.py
  certbot/tests/cli_test.py
  certbot/tests/client_test.py
  certbot/tests/display/obj_test.py
  certbot/tests/display/ops_test.py
  certbot/tests/display/util_test.py
  certbot/tests/eff_test.py
  certbot/tests/main_test.py
  certbot/tests/plugins/dns_common_test.py
  certbot/tests/plugins/enhancements_test.py
  certbot/tests/plugins/manual_test.py
  certbot/tests/plugins/selection_test.py
  certbot/tests/plugins/standalone_test.py
  certbot/tests/plugins/webroot_test.py
  certbot/tests/renewal_test.py
  certbot/tests/renewupdater_test.py
Labels: area: code health

#8934 Finish pinning system rewrite
  acme/setup.py
  certbot-dns-cloudxns/setup.py
  certbot-dns-dnsimple/setup.py
  certbot-dns-dnsmadeeasy/setup.py
  certbot-dns-gehirn/setup.py
  certbot-dns-linode/setup.py
  certbot-dns-luadns/setup.py
  certbot-dns-nsone/setup.py
  certbot-dns-ovh/setup.py
  certbot-dns-sakuracloud/setup.py
  certbot/docs/contributing.rst
  certbot/setup.py
  pytest.ini
  tools/dev_constraints.txt
  tools/merge_requirements.py
  tools/oldest_constraints.txt
  tools/pinning/DESIGN.md
  tools/pinning/common/export-pinned-dependencies.sh
  tools/pinning/current/pyproject.toml
  tools/pinning/current/repin.sh
  tools/pinning/oldest/pyproject.toml
  tools/pinning/oldest/repin.sh
  tools/pinning/pin.sh
  tools/pip_install.py
  tools/requirements.txt
  tox.ini
Labels: area: code health, area: documentation, area: pkging, area: tooling
