Repository certbot/certbot, pull requests merged in 2022-09, with the labels that each got.

#9356 acme: remove Client and BackwardsCompatibleClientV2
  acme/acme/challenges.py
  acme/acme/client.py
  acme/acme/fields.py
  acme/acme/magic_typing.py
  acme/acme/messages.py
  acme/acme/mixins.py
  acme/examples/http01_example.py
  acme/tests/challenges_test.py
  acme/tests/client_test.py
  acme/tests/fields_test.py
  acme/tests/magic_typing_test.py
  acme/tests/messages_test.py
  certbot/certbot/_internal/account.py
  certbot/certbot/_internal/auth_handler.py
  certbot/certbot/_internal/client.py
  certbot/certbot/interfaces.py
  certbot/certbot/tests/acme_util.py
  certbot/tests/auth_handler_test.py
  certbot/tests/client_test.py
  certbot/tests/main_test.py
Labels: area: acme

#9358 unexport attributes in certbot.display.util
  certbot-compatibility-test/certbot_compatibility_test/test_driver.py
  certbot/certbot/_internal/main.py
  certbot/certbot/display/util.py
  certbot/tests/display/obj_test.py
Labels: area: code health

#9314 Removed deprecated functions
  certbot/certbot/tests/util.py
  certbot/certbot/util.py
  certbot/tests/util_test.py
Labels: area: code health

#9315 Remove deprecated functions
  certbot/certbot/compat/misc.py
  certbot/certbot/crypto_util.py
  certbot/tests/compat/misc_test.py
  certbot/tests/crypto_util_test.py
Labels: area: code health

#9417 Fix regression in Cloudflare library
  certbot-dns-cloudflare/certbot_dns_cloudflare/__init__.py
  certbot-dns-cloudflare/certbot_dns_cloudflare/_internal/dns_cloudflare.py
  certbot/CHANGELOG.md
Labels: area: dns

#9262 error out when --reuse-key conflicts with other flags
  certbot-ci/certbot_integration_tests/certbot_tests/assertions.py
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/_internal/storage.py
  certbot/tests/main_test.py
  certbot/tests/renewal_test.py
Labels: area: ui / ux, area: cert management

#9359 plugins: remove support for dist:plugin plugin names
  certbot/certbot/_internal/plugins/disco.py
  certbot/tests/plugins/disco_test.py
Labels: area: ui / ux, area: code health
