Repository certbot/certbot, pull requests merged in 2022-03, with the labels that each got.

#9228 Remove cast for jose.fields.
  acme/setup.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/account.py
  certbot/certbot/_internal/eff.py
  certbot/setup.py
  tools/oldest_constraints.txt
  tools/requirements.txt
Labels: area: mypy

#9233 Add error message to account registration error
  certbot/CHANGELOG.md
  certbot/certbot/_internal/main.py
  certbot/tests/main_test.py
Labels: area: ui / ux

#9252 Add --new-key
  certbot-ci/certbot_integration_tests/certbot_tests/assertions.py
  certbot-ci/certbot_integration_tests/certbot_tests/test_main.py
  certbot/CHANGELOG.md
  certbot/certbot/_internal/cli/__init__.py
  certbot/certbot/_internal/constants.py
  certbot/certbot/_internal/renewal.py
  certbot/certbot/configuration.py
  certbot/tests/main_test.py
  certbot/tests/renewal_test.py
Labels: area: ui / ux, area: cert management, area: renewal
