Repository certbot/certbot, pull requests merged in 2023-03, with the labels that each got.

#9604 google: ignore declare_namespace deprecation warnings
  pytest.ini
Labels: area: testing

#9600 Create Weekly Notification Message for Certbot Team
  .github/workflows/notify_weekly.yaml
Labels: area: tooling

#9601 Create Workflow for Merge Notifications
  .github/workflows/merged.yaml
Labels: area: tooling

#9622 Add async interface for finalization to acme.client.ClientV2
  acme/acme/client.py
  certbot/CHANGELOG.md
Labels: area: acme

#9619 dns-route53: deprecate --dns-route53-propagation-seconds
  certbot-dns-route53/certbot_dns_route53/__init__.py
  certbot-dns-route53/certbot_dns_route53/_internal/dns_route53.py
  certbot-dns-route53/tests/dns_route53_test.py
  certbot/CHANGELOG.md
Labels: area: dns

#9625 Make acme tests internal
  .pylintrc
  acme/MANIFEST.in
  acme/acme/_internal/__init__.py
  acme/acme/_internal/tests/__init__.py
  acme/acme/_internal/tests/challenges_test.py
  acme/acme/_internal/tests/client_test.py
  acme/acme/_internal/tests/crypto_util_test.py
  acme/acme/_internal/tests/errors_test.py
  acme/acme/_internal/tests/fields_test.py
  acme/acme/_internal/tests/jose_test.py
  acme/acme/_internal/tests/jws_test.py
  acme/acme/_internal/tests/messages_test.py
  acme/acme/_internal/tests/standalone_test.py
  acme/acme/_internal/tests/test_util.py
  acme/acme/_internal/tests/testdata/README
  acme/acme/_internal/tests/testdata/cert-100sans.pem
  acme/acme/_internal/tests/testdata/cert-idnsans.pem
  acme/acme/_internal/tests/testdata/cert-ipsans.pem
  acme/acme/_internal/tests/testdata/cert-ipv6sans.pem
  acme/acme/_internal/tests/testdata/cert-nocn.der
  acme/acme/_internal/tests/testdata/cert-san.pem
  acme/acme/_internal/tests/testdata/cert.der
  acme/acme/_internal/tests/testdata/cert.pem
  acme/acme/_internal/tests/testdata/critical-san.pem
  acme/acme/_internal/tests/testdata/csr-100sans.pem
  acme/acme/_internal/tests/testdata/csr-6sans.pem
  acme/acme/_internal/tests/testdata/csr-idnsans.pem
  acme/acme/_internal/tests/testdata/csr-ipsans.pem
  acme/acme/_internal/tests/testdata/csr-ipv6sans.pem
  acme/acme/_internal/tests/testdata/csr-mixed.pem
  acme/acme/_internal/tests/testdata/csr-nosans.pem
  acme/acme/_internal/tests/testdata/csr-san.pem
  acme/acme/_internal/tests/testdata/csr.der
  acme/acme/_internal/tests/testdata/csr.pem
  acme/acme/_internal/tests/testdata/dsa512_key.pem
  acme/acme/_internal/tests/testdata/ec_secp384r1_key.pem
  acme/acme/_internal/tests/testdata/rsa1024_cert.pem
  acme/acme/_internal/tests/testdata/rsa1024_key.pem
  acme/acme/_internal/tests/testdata/rsa2048_cert.pem
  acme/acme/_internal/tests/testdata/rsa2048_key.pem
  acme/acme/_internal/tests/testdata/rsa256_key.pem
  acme/acme/_internal/tests/testdata/rsa4096_cert.pem
  acme/acme/_internal/tests/testdata/rsa4096_key.pem
  acme/acme/_internal/tests/testdata/rsa512_key.pem
  acme/acme/_internal/tests/util_test.py
  mypy.ini
  tox.ini
Labels: area: testing, area: code health, area: python, area: tooling
